/* CHRONICA HARUN · Neon Auth UI v1.0
 * Isolated account layer. Does not patch gameplay, camera, audio, narrative or renderer.
 */
(function(global){
  'use strict';
  const AUTH_URL='https://ep-green-hill-acstnnfu.neonauth.sa-east-1.aws.neon.tech/chronica_harun/auth';
  const DATA_API_URL='https://ep-green-hill-acstnnfu.apirest.sa-east-1.aws.neon.tech/chronica_harun/rest/v1';
  const SDK_URL='https://esm.sh/@neondatabase/neon-js@0.7.0-beta?bundle';
  let controller=null,client=null,modal=null,mode='signin',lastError='';
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  async function waitFor(getter,timeout=20000){const start=Date.now();while(Date.now()-start<timeout){const v=getter();if(v)return v;await sleep(50)}throw new Error('Dependência de autenticação não ficou pronta.');}
  function emit(state){try{global.dispatchEvent(new CustomEvent('chronica:auth-state',{detail:state}))}catch(_){}renderButton();renderModal();return state;}
  function escapeHtml(s){return String(s==null?'':s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function state(){return controller?controller.state():{authenticated:false,user:null,session:null,error:null};}
  function cloudState(){return global.CHRONICA_CLOUD_SYNC&&typeof global.CHRONICA_CLOUD_SYNC.state==='function'?global.CHRONICA_CLOUD_SYNC.state():null;}
  function ensureStyle(){if(document.getElementById('chronicaAuthStyle'))return;const s=document.createElement('style');s.id='chronicaAuthStyle';s.textContent=`#chronicaAccountBtn{border-color:#66502c!important}.chronica-auth-overlay{position:fixed;inset:0;z-index:190000;display:grid;place-items:center;background:rgba(0,0,0,.89);backdrop-filter:blur(8px);padding:18px}.chronica-auth-card{width:min(680px,94vw);max-height:90vh;overflow:auto;border:1px solid #806533;background:linear-gradient(160deg,#15100a,#070605);box-shadow:0 30px 120px #000;padding:26px;color:#e9e0cf;font-family:Georgia,serif}.chronica-auth-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;border-bottom:1px solid #342a1c;padding-bottom:16px}.chronica-auth-head h2{margin:5px 0 0;font-size:30px;color:#f1e6d2}.chronica-auth-eyebrow{font:700 10px Arial,sans-serif;letter-spacing:.18em;color:#b9975d}.chronica-auth-close{font-size:24px!important;min-width:42px}.chronica-auth-tabs,.chronica-auth-actions{display:flex;gap:9px;flex-wrap:wrap;margin:18px 0}.chronica-auth-tabs button.active{border-color:#c09b55!important;color:#f5dcab!important}.chronica-auth-field{display:grid;gap:7px;margin:12px 0}.chronica-auth-field label{font:700 11px Arial,sans-serif;letter-spacing:.08em;color:#b9aa92}.chronica-auth-field input{background:#080706;border:1px solid #463b2b;color:#eee3d1;padding:12px 13px;font:14px Arial,sans-serif;outline:none}.chronica-auth-field input:focus{border-color:#aa864a}.chronica-auth-msg{padding:11px 12px;border:1px solid #493b29;background:#0a0806;color:#c9baa4;line-height:1.45}.chronica-auth-msg.err{border-color:#703c38;color:#e8aaa3}.chronica-auth-cloud{margin-top:20px;padding-top:18px;border-top:1px solid #342a1c}.chronica-auth-cloud strong{color:#e8cd95}.chronica-auth-note{margin-top:18px;color:#9e9588;font-size:13px;line-height:1.55}.chronica-auth-user{font:14px Arial,sans-serif;color:#dec99f}.chronica-auth-actions .danger{border-color:#713b37!important;color:#e8aaa3!important}`;document.head.appendChild(s);}
  function ensureButton(){const host=document.querySelector('.menu-actions');if(!host)return null;let b=document.getElementById('chronicaAccountBtn');if(!b){b=document.createElement('button');b.id='chronicaAccountBtn';b.type='button';b.addEventListener('click',open);host.appendChild(b)}return b;}
  function renderButton(){const b=ensureButton();if(!b)return;const s=state();b.textContent=s.authenticated?'CONTA · NUVEM':'CONTA · LOCAL';b.title=s.authenticated?'Persistência remota autenticada':'Entrar para ativar persistência remota';}
  function syncModeLabel(cs){if(!cs)return'aguardando';return({ready:'sincronizado',conflict:'conflito entre dispositivo e nuvem','local-only':'somente neste dispositivo','remote-only':'somente na nuvem',empty:'sem save',error:'erro de sincronização',unknown:'aguardando'})[cs.mode]||cs.mode;}
  function renderModal(){if(!modal||!document.body.contains(modal))return;const s=state(),cs=cloudState(),body=modal.querySelector('[data-auth-body]');if(!body)return;if(s.authenticated){const email=escapeHtml(s.user&&s.user.email||'usuário autenticado');body.innerHTML=`<div class="chronica-auth-user">Sessão ativa: <strong>${email}</strong></div><div class="chronica-auth-cloud"><div class="chronica-auth-eyebrow">PERSISTÊNCIA DA CAMPANHA</div><p>Estado da nuvem: <strong>${escapeHtml(syncModeLabel(cs))}</strong></p>${cs&&cs.mode==='conflict'?'<div class="chronica-auth-msg">Há um save local e outro remoto diferentes. Escolha explicitamente qual versão deve prevalecer.</div>':''}<div class="chronica-auth-actions"><button data-sync-inspect>VERIFICAR NUVEM</button><button data-sync-upload>ENVIAR ESTE DISPOSITIVO</button><button data-sync-download>BAIXAR DA NUVEM</button><button data-auth-signout class="danger">SAIR DA CONTA</button></div><div data-auth-feedback class="chronica-auth-msg${lastError?' err':''}">${escapeHtml(lastError||'A conta sincroniza a campanha do jogo. Ela não concede nem certifica Grau institucional.')}</div></div>`;}else{body.innerHTML=`<div class="chronica-auth-tabs"><button data-auth-mode="signin" class="${mode==='signin'?'active':''}">ENTRAR</button><button data-auth-mode="signup" class="${mode==='signup'?'active':''}">CRIAR CONTA</button></div>${mode==='signup'?'<div class="chronica-auth-field"><label>NOME</label><input data-auth-name autocomplete="name" maxlength="80"></div>':''}<div class="chronica-auth-field"><label>E-MAIL</label><input data-auth-email type="email" autocomplete="email" maxlength="254"></div><div class="chronica-auth-field"><label>SENHA</label><input data-auth-password type="password" autocomplete="${mode==='signin'?'current-password':'new-password'}" minlength="8"></div><div class="chronica-auth-actions"><button data-auth-submit class="primary">${mode==='signin'?'ENTRAR E ATIVAR NUVEM':'CRIAR CONTA'}</button></div><div data-auth-feedback class="chronica-auth-msg${lastError?' err':''}">${escapeHtml(lastError||'Sem conta, o jogo continua funcionando localmente. Com conta, saves podem ser sincronizados entre sessões e dispositivos.')}</div>`;}bindModalActions();}
  function setFeedback(text,isError){lastError=text||'';const el=modal&&modal.querySelector('[data-auth-feedback]');if(el){el.textContent=lastError;el.classList.toggle('err',!!isError)}}
  function bindModalActions(){if(!modal)return;modal.querySelectorAll('[data-auth-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.authMode;lastError='';renderModal()});const submit=modal.querySelector('[data-auth-submit]');if(submit)submit.onclick=async()=>{const email=modal.querySelector('[data-auth-email]')?.value.trim(),password=modal.querySelector('[data-auth-password]')?.value||'',name=modal.querySelector('[data-auth-name]')?.value.trim();if(!email||password.length<8||(mode==='signup'&&!name)){setFeedback('Preencha os campos. A senha precisa ter pelo menos 8 caracteres.',true);return}submit.disabled=true;try{const s=mode==='signin'?await controller.signIn(email,password):await controller.signUp(name,email,password);lastError='';emit(s);await inspectCloud();}catch(e){setFeedback(e&&e.message?e.message:String(e),true)}finally{submit.disabled=false}};const out=modal.querySelector('[data-auth-signout]');if(out)out.onclick=async()=>{try{await controller.signOut();lastError='';emit(controller.state())}catch(e){setFeedback(e.message||String(e),true)}};const inspect=modal.querySelector('[data-sync-inspect]');if(inspect)inspect.onclick=()=>runCloud('inspect');const up=modal.querySelector('[data-sync-upload]');if(up)up.onclick=()=>runCloud('uploadLocal');const down=modal.querySelector('[data-sync-download]');if(down)down.onclick=()=>runCloud('downloadRemote');}
  async function runCloud(method){const cloud=global.CHRONICA_CLOUD_SYNC;if(!cloud||typeof cloud[method]!=='function'){setFeedback('Módulo de sincronização ainda não ficou pronto.',true);return}try{setFeedback('Processando...',false);const result=await cloud[method]();lastError=method==='downloadRemote'?'Save da nuvem instalado neste dispositivo. Recarregue a página antes de usar CONTINUAR.':'Sincronização concluída.';renderModal();return result}catch(e){setFeedback(e&&e.message?e.message:String(e),true)}}
  async function inspectCloud(){if(global.CHRONICA_CLOUD_SYNC&&typeof global.CHRONICA_CLOUD_SYNC.inspect==='function')try{await global.CHRONICA_CLOUD_SYNC.inspect()}catch(_){}renderModal();}
  function open(){ensureStyle();try{if(document.pointerLockElement)document.exitPointerLock()}catch(_){}if(modal&&document.body.contains(modal)){renderModal();return}modal=document.createElement('section');modal.className='chronica-auth-overlay';modal.innerHTML='<div class="chronica-auth-card"><div class="chronica-auth-head"><div><div class="chronica-auth-eyebrow">CHRONICA HARUN · CONTA</div><h2>PERSISTÊNCIA</h2></div><button class="chronica-auth-close" data-auth-close>×</button></div><div data-auth-body></div><div class="chronica-auth-note">A persistência remota pertence ao jogo. Progressão real da SOCIETAS ELECTORUM só existe quando o processo real correspondente é concluído e confirmado fora da mecânica de jogo.</div></div>';document.body.appendChild(modal);modal.querySelector('[data-auth-close]').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});renderModal();}
  function close(){if(modal){modal.remove();modal=null}lastError='';}
  async function init(){try{ensureStyle();await waitFor(()=>global.CHRONICA_BACKEND_BRIDGE);await waitFor(()=>global.CHRONICA_AUTH_CONTROLLER_FACTORY);const mod=await import(SDK_URL);if(!mod||typeof mod.createClient!=='function')throw new Error('SDK Neon Auth indisponível.');client=mod.createClient({auth:{url:AUTH_URL},dataApi:{url:DATA_API_URL}});controller=global.CHRONICA_AUTH_CONTROLLER_FACTORY.createAuthController({client,bridge:global.CHRONICA_BACKEND_BRIDGE,onState:emit});global.CHRONICA_AUTH=Object.freeze({open,close,refresh:()=>controller.refresh(),signIn:(e,p)=>controller.signIn(e,p),signUp:(n,e,p)=>controller.signUp(n,e,p),signOut:()=>controller.signOut(),state:()=>controller.state(),client});renderButton();await controller.refresh();if(controller.state().authenticated)await inspectCloud();document.documentElement.dataset.chronicaAuth='v1';}catch(error){console.error('[CHRONICA AUTH]',error);document.documentElement.dataset.chronicaAuth='error';}}
  global.addEventListener('chronica:cloud-sync-state',()=>renderModal());
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
