(function(){
'use strict';
const Core=window.HarunSurvivorDebug;if(!Core)return;
let A=window.MUNDUSAudio,lastRun=null,lastEnemies=0,lastShots=0,lastHp=0,lastLevel=0,lastBoss=null,lastState='';
function configure(){A=window.MUNDUSAudio;if(!A)return false;let saved=null;try{saved=localStorage.getItem('mundus_audio_master')}catch(_){}A.configure({game:'survivor',profile:{bpm:118,music:.78,sfx:1.05,ui:.94,amb:.52,brightness:1.12}});if(saved==null)A.setMaster(.92);return true}
function state(name,intensity=.5){if(A&&name!==lastState){lastState=name;A.setState(name,{intensity})}}
function unlock(){if(!A)configure();A?.unlock?.();const st=Core.getState();state(st.state==='run'?'combat':'menu',st.state==='run'?.72:.3)}
window.addEventListener('pointerdown',unlock,{capture:true});window.addEventListener('keydown',unlock,{capture:true});configure();
function loop(){if(!A)configure();const st=Core.getState(),r=st.run;if(st.state==='menu'){state('menu',.28);lastRun=null;lastEnemies=lastShots=0;lastBoss=null}else if(st.state==='run'&&r){if(r!==lastRun){lastRun=r;lastEnemies=r.enemies.length;lastShots=r.shots.length;lastHp=r.player.hp;lastLevel=r.level;lastBoss=r.boss;state('combat',.68);A?.sfx('door',{gain:.9})}if(r.boss&&r.boss!==lastBoss){lastBoss=r.boss;state('boss',.95);A?.sfx('boss_windup',{gain:1.15})}else if(!r.boss&&lastBoss){lastBoss=null;state('combat',.68);A?.sfx('boss_death',{gain:1.15})}if(r.shots.length>lastShots)A?.sfx('attack',{gain:.72,pitch:.95+Math.random()*.12});if(r.enemies.length<lastEnemies)A?.sfx('enemy_death',{gain:.76,pitch:.9+Math.random()*.18});if(r.enemies.some(e=>e.hit>0))A?.sfx('impact',{gain:.5,pitch:.92+Math.random()*.14});if(r.player.hp<lastHp-.05)A?.sfx('player_hurt',{gain:1.05});if(r.level>lastLevel)A?.sfx('level_up',{gain:1});lastEnemies=r.enemies.length;lastShots=r.shots.length;lastHp=r.player.hp;lastLevel=r.level}else if(document.querySelector('#v5Ritual:not([hidden])'))state('ritual',.48);requestAnimationFrame(loop)}
window.addEventListener('mundus:v5:tarot',()=>A?.sfx('arcana',{gain:1.15}));window.addEventListener('mundus:v5:gain',e=>A?.sfx(e.detail?.kind==='pacts'?'ritual_seal':'pickup',{gain:1.05}));
window.HarunV5Audio=Object.freeze({version:'5.0.0',configure,unlock,snapshot:()=>A?.snapshot?.()||null});requestAnimationFrame(loop);
})();