(function(){
'use strict';
const Core=window.HarunSurvivorDebug,S=window.HarunV5Systems;if(!Core||!S)return;const frame=document.querySelector('.frame'),TAU=Math.PI*2;
const catalog=Object.fromEntries(S.familiars.map(x=>[x.id,x]));
const looks={scarab:['✺','#f0c85f'],ibis:['𓅞','#b9ecff'],falcon:['𓅃','#efbe63'],serpent:['ϟ','#7de0a4'],jackal:['𓃥','#d7a970'],beetle:['◆','#90d6c3'],lotus:['✿','#ef9fd0'],sphinx:['◇','#e8b45d'],owl:['◉','#b9b8ff'],lion:['☉','#ffb35c'],raven:['◆','#8d91b8'],moth:['✧','#d7c8ff']};
let canvas=document.querySelector('#v5Companions');if(!canvas){canvas=document.createElement('canvas');canvas.id='v5Companions';canvas.width=540;canvas.height=960;frame.appendChild(canvas)}const ctx=canvas.getContext('2d');let last=performance.now(),lastDraw=0,timers=new Map(),runRef=null;
function nearest(run,from){let best=null,dd=1e9;for(const e of run.enemies){const d=Math.hypot(e.x-from.x,e.y-from.y);if(d<dd){dd=d;best=e}}return best}
function farthest(run,from){let best=null,dd=-1;for(const e of run.enemies){const d=Math.hypot(e.x-from.x,e.y-from.y);if(d>dd){dd=d;best=e}}return best}
function fire(run,x,y,target,damage,color){if(!target)return;const a=Math.atan2(target.y-y,target.x-x);run.shots.push({x,y,vx:Math.cos(a)*390,vy:Math.sin(a)*390,r:4.5,life:1.4,damage,pierce:0,ric:0,burn:0,hit:new Set(),v5Familiar:true,color})}
function position(run,i,n,now){const p=run.player,a=now*.0012+i*TAU/Math.max(1,n),rad=42+(i%2)*12;return{x:p.x+Math.cos(a)*rad,y:p.y+18+Math.sin(a)*rad*.55,a}}
function behavior(run,id,pos,dt){let cd=(timers.get(id)||0)-dt;timers.set(id,cd);if(cd>0)return;const p=run.player,near=nearest(run,pos);switch(id){case'scarab':if(near)near.hp-=p.damage*.75;timers.set(id,1.05);break;case'falcon':fire(run,pos.x,pos.y,farthest(run,pos),p.damage*.72,'#efbe63');timers.set(id,.72);break;case'serpent':if(near)near.poison=Math.max(near.poison||0,2.8);timers.set(id,.8);break;case'lotus':p.hp=Math.min(p.maxHp,p.hp+p.maxHp*.035);timers.set(id,5);break;case'sphinx':if(run.boss)run.boss.hp-=p.damage*1.15;else if(near)near.hp-=p.damage*.5;timers.set(id,1.25);break;case'lion':for(const e of run.enemies)if(Math.hypot(e.x-p.x,e.y-p.y)<125)e.hp-=p.damage*.45;timers.set(id,2.8);break;case'raven':if(near&&near.hp/Math.max(1,near.maxHp)<.18)near.hp-=Math.max(near.hp,p.damage*2);timers.set(id,.65);break;case'moth':p.inv=Math.max(p.inv,.08);timers.set(id,1.4);break;case'ibis':p.crit=Math.max(p.crit,.1);timers.set(id,3.2);break;case'jackal':p.pickup=Math.max(p.pickup,82);timers.set(id,3);break;case'beetle':p.dodge=Math.max(p.dodge,.06);timers.set(id,3);break;case'owl':p.crit=Math.max(p.crit,.08);timers.set(id,3.6);break;default:timers.set(id,1)}}
function drawFamiliar(id,pos,i){const [glyph,color]=looks[id]||['◇','#a8e9d4'];ctx.save();ctx.translate(pos.x,pos.y);ctx.shadowColor=color;ctx.shadowBlur=13;ctx.fillStyle='#071014e8';ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,10+(i%2),0,TAU);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=color;ctx.font='700 11px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(glyph,0,.5);ctx.restore()}
function drawDaimon(run,ids,now){if(!ids.length)return;const p=run.player,id=ids[ids.length-1],a=now*.00045;ctx.save();ctx.globalAlpha=.16;ctx.strokeStyle=id.includes('phosphoros')?'#ffd36b':id.includes('nuit')?'#9fa7ff':'#73e8d0';ctx.lineWidth=2;ctx.setLineDash([5,7]);ctx.beginPath();ctx.arc(p.x,p.y,58+Math.sin(a*5)*3,0,TAU);ctx.stroke();ctx.setLineDash([]);ctx.restore()}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;const st=Core.getState(),run=st.run;if(run!==runRef){runRef=run;timers=new Map()}if(now-lastDraw<33){requestAnimationFrame(loop);return}lastDraw=now;ctx.clearRect(0,0,540,960);if(st.state==='run'&&run){const sys=S.state(),ids=sys.familiars||[];drawDaimon(run,sys.daimons||[],now);ids.slice(0,8).forEach((id,i)=>{const pos=position(run,i,Math.min(8,ids.length),now);behavior(run,id,pos,dt);drawFamiliar(id,pos,i)})}requestAnimationFrame(loop)}
window.HarunV5Companions=Object.freeze({version:'5.1.0',visibleCount:()=>{const st=Core.getState();return st.state==='run'?(S.state().familiars||[]).length:0},catalog});requestAnimationFrame(loop);
})();