(function(){
'use strict';
const frame=document.querySelector('.frame');let revealCount=0;
function decorate(root){if(!root||root.hidden)return;root.classList.add('v6-event-surface');const cards=[...root.querySelectorAll('.skill-card,.v4-choice,.v5-tarot,.v5-system-card,[data-v5-glory]')];cards.forEach((card,i)=>{card.classList.remove('v6-reveal-card');card.style.setProperty('--i',i);requestAnimationFrame(()=>card.classList.add('v6-reveal-card'))});if(cards.length){revealCount++;try{window.MUNDUSAudio?.sfx?.('book',{gain:.8})}catch(_){}}
  let fx=root.querySelector('.v6-event-rays');if(!fx){fx=document.createElement('div');fx.className='v6-event-rays';root.appendChild(fx)}fx.innerHTML='<i></i><i></i><i></i><i></i>';
}
const targets=['#upgrade','#event','#v4Glory','#v4Event','#v5Choice'];for(const sel of targets){const el=document.querySelector(sel);if(!el)continue;new MutationObserver(()=>{if(!el.hidden)setTimeout(()=>decorate(el),20)}).observe(el,{attributes:true,attributeFilter:['hidden'],childList:true,subtree:true})}
const style=document.createElement('style');style.textContent='.v6-event-surface{overflow:hidden}.v6-event-rays{position:absolute;z-index:-1;inset:0;pointer-events:none}.v6-event-rays i{position:absolute;left:50%;top:50%;width:5px;height:62%;transform-origin:50% 0;background:linear-gradient(#ffe6a0aa,transparent);filter:blur(.4px);animation:v6rayflash .9s ease-out both}.v6-event-rays i:nth-child(1){transform:rotate(28deg)}.v6-event-rays i:nth-child(2){transform:rotate(112deg)}.v6-event-rays i:nth-child(3){transform:rotate(208deg)}.v6-event-rays i:nth-child(4){transform:rotate(296deg)}@keyframes v6rayflash{from{opacity:0;height:0}30%{opacity:1}to{opacity:0;height:80%}}';document.head.appendChild(style);
window.HarunV6Events=Object.freeze({version:'6.0.0',decorate,revealCount:()=>revealCount});
})();