(function(){
'use strict';
const Core=window.HarunSurvivorDebug;if(!Core)return;const frame=document.querySelector('.frame'),TAU=Math.PI*2;
let canvas=document.querySelector('#v6Feel');if(!canvas){canvas=document.createElement('canvas');canvas.id='v6Feel';canvas.width=540;canvas.height=960;frame.appendChild(canvas)}const c=canvas.getContext('2d');
let last=performance.now(),enemySnap=new Map(),shotSnap=new WeakMap(),lastRun=null,lastHp=null,lastInv=0,bossRef=null,bossBirth=0,fx=[],feedback={hit:0,crit:0,heal:0,block:0,death:0,boss:0};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function ring(x,y,r,color,life=.45){fx.push({kind:'ring',x,y,r,color,life,max:life})}
function burst(x,y,color='#ffe36a',life=.38){fx.push({kind:'burst',x,y,color,life,max:life,seed:Math.random()*99})}
function puff(x,y,color='#cfeeff',life=.52){fx.push({kind:'puff',x,y,color,life,max:life,seed:Math.random()*99});feedback.death++}
function pushText(type,x,y,value){const el=document.createElement('div');el.className=`v6-floating ${type}`;el.textContent=type==='block'?'BLOQUEIO':type==='heal'?`+${Math.max(1,Math.round(value))}`:`${Math.max(1,Math.round(value))}`;el.style.left=`${x/540*100}%`;el.style.top=`${y/960*100}%`;frame.appendChild(el);setTimeout(()=>el.remove(),760);feedback[type]=(feedback[type]||0)+1}
function screenPunch(){frame.classList.remove('v6-screen-punch');void frame.offsetWidth;frame.classList.add('v6-screen-punch')}
function audio(name,gain){try{window.MUNDUSAudio?.sfx?.(name,gain?{gain}:undefined)}catch(_){}}
function reset(run){enemySnap=new Map();shotSnap=new WeakMap();lastRun=run;lastHp=run?.player?.hp??null;lastInv=run?.player?.inv||0;bossRef=null;bossBirth=0;fx.length=0}
function inspect(run,now){const p=run.player;if(lastHp!=null){if(p.hp>lastHp+.02){pushText('heal',p.x,p.y-34,p.hp-lastHp);audio('pickup',.75)}else if(p.hp<lastHp-.02){pushText('crit',p.x,p.y-28,lastHp-p.hp);screenPunch();audio('damage',1.1)}else if(p.inv>lastInv+.08&&lastInv<.05){pushText('block',p.x,p.y-28,0);audio('ui_back',.75)}}lastHp=p.hp;lastInv=p.inv;
  const live=new Set(run.enemies);for(const e of run.enemies){const prev=enemySnap.get(e);if(!prev){enemySnap.set(e,{hp:e.hp,x:e.x,y:e.y});burst(e.x,e.y,'#8dd9ff',.22);continue}const delta=prev.hp-e.hp;if(delta>.03){const crit=delta>(p.damage||1)*1.38;pushText(crit?'crit':'hit',e.x,e.y-e.r-12,delta);burst(e.x,e.y,crit?'#ff6a49':'#ffe36a',crit?.34:.2);if(crit){screenPunch();audio('impact',1.1)}}prev.hp=e.hp;prev.x=e.x;prev.y=e.y}
  for(const [e,s] of [...enemySnap])if(!live.has(e)){puff(s.x,s.y,e?.kind==='boss'?'#ff779e':'#d9efff',e?.kind==='boss'?.85:.5);enemySnap.delete(e)}
  if(run.boss&&run.boss!==bossRef){bossRef=run.boss;bossBirth=now;feedback.boss++;ring(run.boss.x,run.boss.y,86,'#cf67ff',1.1);burst(run.boss.x,run.boss.y,'#ff72c8',.85);audio('boss',1.2)}if(!run.boss)bossRef=null;
  if(run.skills?.meteor_poison&&now-(run._v6MeteorVis||0)>1850&&run.enemies.length){run._v6MeteorVis=now;const e=run.enemies[(Math.random()*run.enemies.length)|0];ring(e.x,e.y,38,'#8cff6c',.8)}
}
function drawShotTrails(run){c.save();c.globalCompositeOperation='lighter';for(const s of [...run.shots,...run.enemyShots]){const prev=shotSnap.get(s);if(prev){const col=s.enemy?'#ff5c7e':s.color||'#ffe77a';const g=c.createLinearGradient(prev.x,prev.y,s.x,s.y);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(1,col);c.strokeStyle=g;c.lineWidth=s.enemy?3:4;c.lineCap='round';c.beginPath();c.moveTo(prev.x,prev.y);c.lineTo(s.x,s.y);c.stroke()}shotSnap.set(s,{x:s.x,y:s.y})}c.restore()}
function drawFx(dt,run,now){c.clearRect(0,0,540,960);drawShotTrails(run);for(const e of run.enemies){if(e.poison>0){c.save();c.globalAlpha=.18+.08*Math.sin(now*.01);c.fillStyle='#59ff74';c.beginPath();c.arc(e.x,e.y,e.r+10,0,TAU);c.fill();c.restore()}if(e.burn>0){for(let i=0;i<2;i++){const a=now*.004+i*3.1;c.fillStyle='rgba(255,126,42,.55)';c.beginPath();c.arc(e.x+Math.cos(a)*e.r*.5,e.y-e.r*.35+Math.sin(a*1.7)*5,2.5,0,TAU);c.fill()}}}
  const p=run.player,near=run.enemies.filter(e=>Math.hypot(e.x-p.x,e.y-p.y)<85).length;if(near>=6){c.save();c.strokeStyle='rgba(255,239,184,.78)';c.lineWidth=3;c.shadowColor='#ffe5a0';c.shadowBlur=18;c.beginPath();c.arc(p.x,p.y,24+Math.sin(now*.012)*2,0,TAU);c.stroke();c.restore()}
  if(run.boss&&bossBirth){const age=(now-bossBirth)/1000;if(age<1.15){const k=clamp(age/1.15,0,1),r=130*(1-k)+48;c.save();c.globalAlpha=1-k*.65;c.strokeStyle='#e473ff';c.lineWidth=5*(1-k)+1;c.beginPath();c.arc(run.boss.x,run.boss.y,r,0,TAU);c.stroke();for(let i=0;i<8;i++){const a=i*TAU/8+age*2;c.beginPath();c.moveTo(run.boss.x+Math.cos(a)*r*.45,run.boss.y+Math.sin(a)*r*.45);c.lineTo(run.boss.x+Math.cos(a)*r,run.boss.y+Math.sin(a)*r);c.stroke()}c.restore()}}
  for(const f of fx){f.life-=dt;const k=clamp(f.life/f.max,0,1);if(f.kind==='ring'){c.save();c.globalAlpha=k;c.strokeStyle=f.color;c.lineWidth=2+4*k;c.beginPath();c.arc(f.x,f.y,f.r*(1.45-k*.45),0,TAU);c.stroke();c.restore()}else if(f.kind==='burst'){c.save();c.translate(f.x,f.y);c.globalAlpha=k;c.strokeStyle=f.color;c.lineWidth=2;for(let i=0;i<9;i++){const a=i*TAU/9+f.seed;c.beginPath();c.moveTo(Math.cos(a)*5,Math.sin(a)*5);c.lineTo(Math.cos(a)*(8+26*(1-k)),Math.sin(a)*(8+26*(1-k)));c.stroke()}c.restore()}else if(f.kind==='puff'){c.save();c.globalAlpha=k*.7;c.fillStyle=f.color;for(let i=0;i<8;i++){const a=i*TAU/8+f.seed;const r=(1-k)*24+5;c.beginPath();c.arc(f.x+Math.cos(a)*r,f.y+Math.sin(a)*r,3+4*k,0,TAU);c.fill()}c.restore()}}fx=fx.filter(f=>f.life>0)}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;const st=Core.getState(),run=st.run;if(run!==lastRun)reset(run);if(st.state==='run'&&run){inspect(run,now);drawFx(dt,run,now)}else c.clearRect(0,0,540,960);requestAnimationFrame(loop)}
window.HarunV6Feel=Object.freeze({version:'6.0.0',pushText,burst,ring,stats:()=>({...feedback,fx:fx.length})});requestAnimationFrame(loop);
})();