(function(){
'use strict';
const Core=window.HarunSurvivorDebug,D=window.HarunSurvivorData;if(!Core||!D)return;const frame=document.querySelector('.frame'),KEY='mundus_harun_survivor_v6_meta';
const slots=['arma','manto','amuleto','anel','botas','reliquia'];const slotIcons={arma:'⚔',manto:'♜',amuleto:'◉',anel:'◇',botas:'⌁',reliquia:'✦'};
const items=[
{id:'wand_1',slot:'arma',name:'Cetro de Thoth',icon:'⚕',rarity:'rare',atk:12},{id:'blade_1',slot:'arma',name:'Lâmina Phosphoros',icon:'†',rarity:'epic',atk:18},{id:'mantle_1',slot:'manto',name:'Manto do Limiar',icon:'♜',rarity:'rare',hp:20},{id:'mantle_2',slot:'manto',name:'Véu de Nuit',icon:'☾',rarity:'epic',hp:28},{id:'amulet_1',slot:'amuleto',name:'Olho de Thoth',icon:'◉',rarity:'rare',atk:7},{id:'ring_1',slot:'anel',name:'Anel Electorum',icon:'◌',rarity:'epic',atk:9},{id:'boots_1',slot:'botas',name:'Passo de Cinza',icon:'⌁',rarity:'rare',hp:12},{id:'relic_1',slot:'reliquia',name:'Selo Solar',icon:'☉',rarity:'legend',atk:16,hp:16},
{id:'scarab_relic',slot:'reliquia',name:'Escaravelho de Ouro',icon:'✺',rarity:'rare',hp:8},{id:'moon_ring',slot:'anel',name:'Anel Lunar',icon:'◔',rarity:'rare',atk:5},{id:'jackal_boots',slot:'botas',name:'Botas de Anúbis',icon:'𓃥',rarity:'epic',hp:18},{id:'ibis_charm',slot:'amuleto',name:'Pena do Íbis',icon:'𓅞',rarity:'epic',atk:11}
];
const talents=[
{id:'iron_wall',name:'Muralha de Ferro',icon:'⛨',effect:'Sopro Vital +4%',stars:1},{id:'healing',name:'Cura',icon:'⚗',effect:'Curas +8%',stars:1},{id:'titan',name:'Titã',icon:'♜',effect:'Dano em elites +7%',stars:1},{id:'crit',name:'Taxa Crítica',icon:'✹',effect:'Crítico +3%',stars:1},{id:'critdmg',name:'Dano Crítico',icon:'△',effect:'Dano crítico +8%',stars:1},{id:'dodge',name:'Desvio',icon:'↝',effect:'Esquiva +3%',stars:1},{id:'vigor',name:'Vigor',icon:'♥',effect:'Sopro +10',stars:2},{id:'strength',name:'Força',icon:'⚔',effect:'Ataque +5%',stars:2},{id:'recovery',name:'Recuperação',icon:'✚',effect:'Recuperação +5%',stars:2},{id:'ward',name:'Égide',icon:'◈',effect:'Bloqueio +3%',stars:2},{id:'fortune',name:'Fortuna',icon:'☸',effect:'Drops +6%',stars:2},{id:'daimon',name:'Voz do Daimon',icon:'ϟ',effect:'Cadência +4%',stars:3}
];
function defaults(){return{energy:30,maxEnergy:30,coins:120,checkin:[],lastCheckDate:'',missions:{daily_wave:0,daily_kills:0,weekly_boss:0},claimed:{},ownedItems:['wand_1','mantle_1','amulet_1','ring_1','boots_1','scarab_relic'],equipped:{arma:'wand_1',manto:'mantle_1',amuleto:'amulet_1',anel:'ring_1',botas:'boots_1',reliquia:'scarab_relic'},itemLevels:{},talentOwned:['iron_wall','healing'],talentStars:{iron_wall:1,healing:1},newFlags:{equipment:true,talents:true,jornada:true},runsSeen:0}}
function load(){try{return Object.assign(defaults(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(_){return defaults()}}let meta=load();function save(){localStorage.setItem(KEY,JSON.stringify(meta))}
function coreMeta(){return Core.getState().meta||{}}
function essence(){return Math.floor(coreMeta().essence||0)}
function power(){let p=900;for(const id of Object.values(meta.equipped)){const it=items.find(x=>x.id===id);if(it)p+=(it.atk||0)*22+(it.hp||0)*7+(meta.itemLevels[id]||0)*35}for(const id of meta.talentOwned)p+=55*(meta.talentStars[id]||1);return Math.round(p)}
let root=document.querySelector('#v6Meta');if(!root){root=document.createElement('section');root.id='v6Meta';root.hidden=true;frame.appendChild(root)}
let nav=document.querySelector('#v6MetaNav');if(!nav){nav=document.createElement('nav');nav.id='v6MetaNav';nav.className='v6-meta-nav';nav.hidden=true;nav.innerHTML='<button data-v6tab="campaign" class="on"><i>⚔</i>CAMPANHA</button><button data-v6tab="equipment"><i>♜</i>EQUIPAMENTO<span class="v6-dot"></span></button><button data-v6tab="talents"><i>◇</i>TALENTOS<span class="v6-dot"></span></button><button data-v6tab="journey"><i>☸</i>JORNADA<span class="v6-dot"></span></button><button data-v6tab="codex"><i>☰</i>CÓDICE</button>';frame.appendChild(nav)}
let current='campaign',lastState='menu',lastRun=null,endShownFor=null;
function header(){return `<header class="v6-meta-top"><div class="v6-profile"><div class="v6-avatar">H</div><div><b>HĀRŪN · NÍVEL ${Math.max(1,coreMeta().bestLevel||1)}</b><small>PODER ${power()}</small></div></div><div class="v6-res"><small>ENERGIA</small><b>ϟ ${meta.energy}/${meta.maxEnergy}</b></div><div class="v6-res"><small>MOEDAS</small><b>◆ ${meta.coins}</b></div><div class="v6-res"><small>ESSÊNCIA</small><b>✦ ${essence()}</b></div></header>`}
function campaign(){return `<div class="v6-meta-body"><section class="v6-hero-panel"><div class="sigil">☉</div><h2>CIDADELA VIVA</h2></section><div class="v6-meta-grid"><button class="v6-tile" data-action="play"><i>⚔</i><b>TRAVESSIA</b><small>continuar jornada</small></button><button class="v6-tile" data-tabjump="equipment"><i>♜</i><b>ARSENAL</b><small>${meta.ownedItems.length} itens</small></button><button class="v6-tile" data-tabjump="talents"><i>◇</i><b>TALENTOS</b><small>${meta.talentOwned.length}/${talents.length}</small></button><button class="v6-tile" data-tabjump="journey"><i>☸</i><b>JORNADA</b><small>recompensas</small></button></div><div class="v6-meta-grid"><div class="v6-tile"><i>◉</i><b>MELHOR ONDA</b><small>${coreMeta().bestWave||0}</small></div><div class="v6-tile"><i>♛</i><b>VITÓRIAS</b><small>${coreMeta().victories||0}</small></div><div class="v6-tile"><i>✦</i><b>COLEÇÃO</b><small>${(coreMeta().collection||[]).length}</small></div><div class="v6-tile"><i>☾</i><b>RUNS</b><small>${coreMeta().runs||0}</small></div></div></div>`}
function equipment(){const eq=slots.map(s=>{const id=meta.equipped[s],it=items.find(x=>x.id===id);return `<div class="v6-slot ${it?.rarity||''}" title="${s}">${it?.icon||slotIcons[s]}</div>`}).join('');const inv=meta.ownedItems.map(id=>{const it=items.find(x=>x.id===id);if(!it)return'';return `<button class="v6-item ${it.rarity}" data-equip="${id}" title="${it.name}">${it.icon}<small>Lv.${1+(meta.itemLevels[id]||0)}</small></button>`}).join('');return `<div class="v6-meta-body"><h3>EQUIPAMENTO</h3><div class="v6-equip-layout"><div class="v6-slots">${eq}</div><div><div class="v6-item-grid">${inv}</div><button class="v6-draw" data-action="forge" style="margin-top:12px">FORJAR ITEM · 20 ESSÊNCIA</button></div></div></div>`}
function talentsView(){const cards=talents.map(t=>{const owned=meta.talentOwned.includes(t.id),stars=meta.talentStars[t.id]||0;return `<article class="v6-talent-card ${owned?'':'v6-locked'}"><i>${t.icon}</i><b>${t.name}</b><div class="v6-stars">${'★'.repeat(stars)}${'☆'.repeat(Math.max(0,3-stars))}</div><small>${owned?t.effect:'NÃO DESCOBERTO'}</small></article>`}).join('');return `<div class="v6-meta-body"><h3>CARTAS DE TALENTO</h3><div class="v6-talent-grid">${cards}</div><button class="v6-draw" data-action="drawTalent" style="width:100%;margin-top:14px">SORTEAR · 40 ESSÊNCIA</button></div>`}
function today(){return new Date().toISOString().slice(0,10)}
function journey(){const days=Array.from({length:14},(_,i)=>{const d=i+1,claimed=meta.checkin.includes(d);return `<button class="v6-check ${claimed?'claimed':''}" data-check="${d}" ${claimed?'disabled':''}><b>${String(d).padStart(2,'0')}</b><div>${d%7===0?'✦ 25':d%3===0?'◆ 150':'✦ 8'}</div></button>`}).join('');const missions=[['daily_wave','Vença 10 ondas',10,'✦ 10'],['daily_kills','Derrote 80 inimigos',80,'◆ 120'],['weekly_boss','Derrote 3 chefes',3,'✦ 30']];return `<div class="v6-meta-body"><h3>CHECK-IN · 14 DIAS</h3><div class="v6-check-grid">${days}</div><h3>MISSÕES</h3>${missions.map(m=>{const v=meta.missions[m[0]]||0,done=v>=m[2],claimed=meta.claimed[m[0]];return `<div class="v6-mission"><div><b>${m[1]}</b><small>${Math.min(v,m[2])}/${m[2]} · ${m[3]}</small></div><button data-mission="${m[0]}" ${!done||claimed?'disabled':''}>${claimed?'RECEBIDO':'RECEBER'}</button></div>`}).join('')}</div>`}
function codex(){const s=Core.getState().meta?.v5Systems||{};return `<div class="v6-meta-body"><h3>CÓDICE</h3><div class="v6-meta-grid"><div class="v6-tile"><i>☿</i><b>TAROT</b><small>${s.tarotOwned?.length||0}/78</small></div><div class="v6-tile"><i>𓅃</i><b>FAMILIARES</b><small>${s.familiars?.length||0}/12</small></div><div class="v6-tile"><i>♛</i><b>DAIMONS</b><small>${s.daimons?.length||0}</small></div><div class="v6-tile"><i>☠</i><b>BESTIÁRIO</b><small>${s.bestiary?.length||0}</small></div></div></div>`}
function render(){root.innerHTML=header()+`<section class="v6-panel ${current==='campaign'?'on':''}">${campaign()}</section><section class="v6-panel ${current==='equipment'?'on':''}">${equipment()}</section><section class="v6-panel ${current==='talents'?'on':''}">${talentsView()}</section><section class="v6-panel ${current==='journey'?'on':''}">${journey()}</section><section class="v6-panel ${current==='codex'?'on':''}">${codex()}</section>`;nav.querySelectorAll('[data-v6tab]').forEach(b=>b.classList.toggle('on',b.dataset.v6tab===current));for(const b of root.querySelectorAll('[data-tabjump]'))b.onclick=()=>open(b.dataset.tabjump);const play=root.querySelector('[data-action="play"]');if(play)play.onclick=()=>{if(meta.energy<=0)return;meta.energy--;save();document.querySelector('#startQuick')?.click()};const forge=root.querySelector('[data-action="forge"]');if(forge)forge.onclick=forgeItem;const draw=root.querySelector('[data-action="drawTalent"]');if(draw)draw.onclick=drawTalent;root.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(b.dataset.equip));root.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>claimCheckin(+b.dataset.check));root.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>claimMission(b.dataset.mission));updateDots()}
function open(tab='campaign'){const changed=current!==tab||root.hidden;current=tab;meta.newFlags[tab]=false;root.hidden=false;nav.hidden=false;if(changed)render();else updateDots()}
function close(){root.hidden=true;nav.hidden=true}
nav.querySelectorAll('[data-v6tab]').forEach(b=>b.onclick=()=>open(b.dataset.v6tab));
function equip(id){const it=items.find(x=>x.id===id);if(!it)return;meta.equipped[it.slot]=id;meta.newFlags.equipment=false;save();render()}
function forgeItem(){const cm=coreMeta();if((cm.essence||0)<20)return;cm.essence-=20;const locked=items.filter(x=>!meta.ownedItems.includes(x.id));if(locked.length)meta.ownedItems.push(locked[(Math.random()*locked.length)|0].id);else{const id=meta.ownedItems[(Math.random()*meta.ownedItems.length)|0];meta.itemLevels[id]=(meta.itemLevels[id]||0)+1}localStorage.setItem(D.metaKey,JSON.stringify(cm));save();render()}
function drawTalent(){const cm=coreMeta();if((cm.essence||0)<40)return;cm.essence-=40;const pool=talents.filter(x=>!meta.talentOwned.includes(x.id));const t=(pool.length?pool:talents)[(Math.random()*(pool.length?pool:talents).length)|0];if(!meta.talentOwned.includes(t.id))meta.talentOwned.push(t.id);meta.talentStars[t.id]=Math.min(3,(meta.talentStars[t.id]||0)+1);localStorage.setItem(D.metaKey,JSON.stringify(cm));meta.newFlags.talents=false;save();render()}
function claimCheckin(day){if(meta.checkin.includes(day))return false;if(meta.lastCheckDate===today())return false;meta.checkin.push(day);meta.lastCheckDate=today();if(day%7===0){const cm=coreMeta();cm.essence=(cm.essence||0)+25;localStorage.setItem(D.metaKey,JSON.stringify(cm))}else if(day%3===0)meta.coins+=150;else{const cm=coreMeta();cm.essence=(cm.essence||0)+8;localStorage.setItem(D.metaKey,JSON.stringify(cm))}save();render();return true}
function claimMission(id){if(meta.claimed[id])return false;const req={daily_wave:10,daily_kills:80,weekly_boss:3}[id]||999;if((meta.missions[id]||0)<req)return false;meta.claimed[id]=true;if(id==='daily_kills')meta.coins+=120;else{const cm=coreMeta();cm.essence=(cm.essence||0)+(id==='weekly_boss'?30:10);localStorage.setItem(D.metaKey,JSON.stringify(cm))}save();render();return true}
function updateDots(){for(const b of nav.querySelectorAll('[data-v6tab]')){const d=b.querySelector('.v6-dot');if(d)d.hidden=!meta.newFlags[b.dataset.v6tab]}}
function confetti(host){for(let i=0;i<36;i++){const q=document.createElement('i');q.className='v6-confetti';q.style.left=`${Math.random()*100}%`;q.style.top=`${-10-Math.random()*35}px`;q.style.setProperty('--cc',['#ff496a','#5de5ff','#ffe264','#b46cff','#65f08a'][i%5]);q.style.animationDelay=`${Math.random()*.5}s`;host.appendChild(q)}}
function endSummary(run){let end=document.querySelector('#v6End');if(!end){end=document.createElement('section');end.id='v6End';end.className='v6-end';frame.appendChild(end)}end.hidden=false;const score=Math.max(1,Math.round((run.wave||1)/4));end.innerHTML=`<div class="v6-end-card"><div class="v6-end-badge">${score}</div><h2>${run.wave>=50?'TRAVESSIA CONCLUÍDA':'FIM DA TRAVESSIA'}</h2><p>ONDA ${run.wave} · NÍVEL ${run.level} · ${run.coins} MOEDAS</p><div class="v6-end-rewards"><span>✦ ${Math.max(4,Math.floor((run.essenceRun||0)*.6))}</span><span>◆ ${run.coins}</span></div><small>TOQUE PARA CONTINUAR</small></div>`;confetti(end);end.onclick=()=>{end.hidden=true;open('campaign')}}
function trackProgress(run){if(!run)return;meta.missions.daily_wave=Math.max(meta.missions.daily_wave,Math.min(10,run.wave));meta.missions.daily_kills=Math.max(meta.missions.daily_kills,Math.min(80,(run._v6Kills||0)));if(run.wave%10===1&&run.wave>1&&run._v6BossCountedWave!==run.wave){run._v6BossCountedWave=run.wave;meta.missions.weekly_boss=Math.min(3,(meta.missions.weekly_boss||0)+1);save()}}
let prevEnemyCount=0;function loop(){const st=Core.getState(),run=st.run;if(st.state==='run'&&run){close();if(lastRun!==run){lastRun=run;prevEnemyCount=run.enemies.length}if(run.enemies.length<prevEnemyCount)run._v6Kills=(run._v6Kills||0)+(prevEnemyCount-run.enemies.length);prevEnemyCount=run.enemies.length;trackProgress(run)}else if(st.state==='menu'){if(lastState==='run'&&lastRun&&!lastRun.v6VoluntaryLeave&&!endShownFor?.has?.(lastRun)){endShownFor=endShownFor||new WeakSet();endShownFor.add(lastRun);save();endSummary(lastRun)}else if(document.querySelector('#v6End')?.hidden!==false&&root.hidden)open(current)}lastState=st.state;requestAnimationFrame(loop)}
window.HarunV6Meta=Object.freeze({version:'6.0.0',open,state:()=>JSON.parse(JSON.stringify(meta)),claimCheckin,claimMission,power,items,talents});render();requestAnimationFrame(loop);
})();