(function(){
'use strict';
const D=window.HarunSurvivorData,Core=window.HarunSurvivorDebug;
if(!D||!Core) throw new Error('Canonical progression requires Survivor core');
const $=s=>document.querySelector(s),campaign=$('#campaign'),quick=$('#startQuick');
if(!campaign)return;
const debugMode=new URLSearchParams(location.search).has('debug');
const ROMAN=['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI','XXII','XXIII','XXIV','XXV','XXVI','XXVII','XXVIII','XXIX','XXX','XXXI','XXXII','XXXIII'];
const fractal=['Caverna','Revelação','Ruptura','Limiar','Travessia','Provação','Reintegração','Encarnar','Obra','Passagem'];

// Os 16 mapas já existentes são preservados como INGRESSUS LÚDICO DO JOGO.
// Isto NÃO declara equivalência com o currículo institucional da Societas.
const ingressusRaw=[
 ['o_olho','O OLHO','PERCEPÇÃO','discernimento, atenção e visão do oculto','blind_observer','revelatory_eye'],
 ['a_chama','A CHAMA','REGÊNCIA','governo interno, foco e comando','impulse_archon','black_flame_matrix'],
 ['a_fundacao','A FUNDAÇÃO','ESTRUTURA','base, limite e sustentação','inert_stone_guardian','foundation_hammer'],
 ['a_eleicao','A ELEIÇÃO','AUTOELEIÇÃO','escolha consciente contra reflexo de massa','seal_of_no','election_sigil'],
 ['a_balanca','A BALANÇA','AUTORRESPONSABILIDADE','custo, consequência e proporção','mask_collector','inner_balance'],
 ['a_vontade','A VONTADE','VERDADEIRA VONTADE','direção própria contra desejo implantado','false_daimon','will_vector'],
 ['o_carater','O CARÁTER','CARÁTER','coerência entre palavra, ato e pressão','stone_witness','character_column'],
 ['a_disciplina','A DISCIPLINA','DISCIPLINA','ritmo, repetição e constância sob atrito','rhythm_devourer','discipline_rhythm'],
 ['a_clareza','A CLAREZA','CLAREZA','redução de ruído e leitura de causalidade','clouding_one','clarity_light'],
 ['a_transmutacao','A TRANSMUTAÇÃO','TRANSMUTAÇÃO','converter dano, escória e conflito em recurso','slag_dragon','transmutation_serpent'],
 ['o_corpo','O CORPO','CORPO E ENERGIA','sustentar ação sem colapso de recurso','exhaustion_tyrant','vital_pulse'],
 ['a_obra','A OBRA','OBRA','construir forma externa a partir da direção interna','blind_architect','hand_of_work'],
 ['a_fortuna','A FORTUNA','FORTUNA','troca, risco e recursos sem servidão ao acaso','archontic_banker','sigillar_fortune'],
 ['a_influencia','A INFLUÊNCIA','INFLUÊNCIA','voz, comando e contágio social sem dissolução','approval_chorus','verbum'],
 ['o_legado','O LEGADO','LEGADO','memória, nome e continuidade que sobrevivem ao ciclo','durable_name_guardian','memoria_ignis'],
 ['actus_ingressus_chamber','CÂMARA DO ACTUS INGRESSUS','ACTUS INGRESSUS','síntese lúdica do Ingressus e passagem para a condição Estudante','initiation_throne','memoria_ignis']
];
const ingressus=ingressusRaw.map((x,i)=>({id:x[0],name:x[1],subtitle:x[2],desc:x[3],bossId:x[4],powerId:x[5],index:i,kind:i===15?'rite':(i>12?'gate':'stage')}));

// Estudante: etapa preparatória de 99 dias, nunca Grau.
const student=[
 ['xi1','XI·1 · O OLHO / PERCEPÇÃO I','Perceber antes de concluir.'],['xi2','XI·2 · O OLHO / PERCEPÇÃO II','Atenção, linguagem e teste de realidade.'],['xi3','XI·3 · O OLHO / PERCEPÇÃO III','Metapercepção e discriminação.'],['period1','PROVA DE PASSAGEM · PERÍODO I','Transferência da percepção para uma convicção real.'],
 ['xi4','XI·4 · A CHAMA / REGÊNCIA I','Escolher o centro que governa.'],['xi5','XI·5 · A CHAMA / REGÊNCIA II','Interromper automatismos e assumir autoria.'],['xi6','XI·6 · A CHAMA / REGÊNCIA III','Regência, decisão e consequência.'],['period2','PROVA DE PASSAGEM · PERÍODO II','Transformar padrão automático em ação deliberada.'],
 ['xi7','XI·7 · A OBRA I','Fazer a consciência tocar o mundo.'],['xi8','XI·8 · A OBRA II','Continuidade, execução e revisão.'],['xi9','XI·9 · A OBRA III','Transferência e integração da Obra inicial.'],['period3','PROVA DE PASSAGEM · PERÍODO III','Concluir Obra inicial pequena, verificável e explicável.'],
 ['regencia','GATE DE REGÊNCIA','Autoria, ética e integridade são gates não compensáveis.'],['dossie','Dossiê','Consolidar evidências da etapa formativa.'],['exame','EXAME INDIVIDUAL','Passagem por competência para Peregrinus Ignis ou remediação.']
].map((x,i)=>({id:x[0],name:x[1],desc:x[2],index:i,kind:x[0].startsWith('period')||['regencia','dossie','exame'].includes(x[0])?'gate':'stage'}));

const peregrinus=[
 ['Autoeleição','Romper identidade puramente recebida e assumir autoria.'],['Autorresponsabilidade','Converter desculpa em capacidade de resposta sem negar contexto.'],['Verdadeira Vontade','Distinguir impulso, desejo, pressão externa e direção estável.'],['Caráter','Reduzir a distância entre valor declarado e conduta repetida.'],['Disciplina','Tornar a ação menos dependente do estado momentâneo.'],['Clareza','Refinar discriminação, linguagem, metapercepção e revisão de modelos.'],['Transmutação','Converter conflito, sombra e fricção em recurso de integração e ação.'],['Corpo e Energia','Interocepção, presença, regulação e linguagem energética responsável.'],['Obra','Converter Vontade em construção concreta e sustentável.'],['Fortuna','Trabalhar oportunidade, preparação, probabilidade e recursos.'],['Influência','Linguagem, presença, reciprocidade, persuasão e limite ético.'],['Legado','Investigar o que permanece no mundo, nos outros e nas instituições.'],['Forja do Pergaminho Pessoal','Síntese autoral testável, revisável e situada.']
].map((x,i)=>({id:`g1_${i+1}`,name:x[0],desc:x[1],index:i,kind:i===12?'gate':'scroll'}));

const profiles={
 1:['Peregrinus Ignis','Entrada, compromisso, continuidade, estudo geral e registro cuidadoso.','Fogo inicial e registro de prova'],2:['Neophyte','Visão simbólica, imaginação, percepção e discernimento.','Oculus Hori'],3:['Architectus','Fundamentos corporais, respiração, disciplina, precisão e estabilidade.','Architectus Fundamentorum'],4:['Practicus','Cabala, correspondências, intelecto, pesquisa e divinação.','Draconis · operação reservada'],5:['Philosophus','Formação moral, desejo, devoção, valores e vontade.','Sol Internus'],6:['Dominus Liminis','Síntese, concentração, domínio da atenção e permanência no limiar.','Lamina Voluntatis'],7:['Adeptus Minor','Direção central, Daimon Interior e Verdadeira Vontade.','Ritual do Daimon Interior'],8:['Clavis Potestatis','Magia prática, poder aplicado, Obra, sistemas e governança.','Chave do poder aplicado'],9:['Adeptus Exemptus','Autossuficiência, tese, método e transmissão.','Horus Invictus · máscara'],10:['Magister Templi','Compreensão, dissolução, silêncio e transmissão responsável.','Aurora Lux Ferre'],11:['Magus','Palavra, Lei, corpus autoral, responsabilidade e legado.','Vigil Liminis · transição'],
 12:['Lilith','Entrada no desconhecido com aterramento, vontade e limites.','Porta Ignoti'],13:['Gamaliel','Sonhos, imaginação, inconsciente e campo lunar.','Somnia Noctis'],14:['Samael','Pensamento independente, ruptura de certezas e discernimento.','Sapientia Sinistra'],15:['A’arab Zaraq','Desejo, beleza, erotismo consciente, coragem e continuidade criativa.','Bellator Veneris'],16:['Thagirion','Integração das polaridades e formação do centro solar sombrio.','Sol Niger'],17:['Golachab','Ruptura, sofrimento, impulsos destrutivos e transmutação responsável.','Transmutatio Ignea'],18:['Gha’agsheblah','Consolidação do trabalho e preparação para o Abismo.','Vigilia Abyssi'],19:['Satariel','Visão draconiana, leitura de padrões e percepção estratégica.','Apertio Draconis'],20:['Ghagiel','Lucidez convertida em direção luciferiana materializada.','Stella Luciferi'],21:['Thaumiel','Soberania, criação, poder, autoridade e consequência.','Promissum Serpentis'],22:['Adamas Ater','Fechamento provisório da Segunda Ordem e preparação da nova criação.','Creatio Nova · provisório'],33:['Ipsissimus','Ápice nominal do sistema; conteúdo interno reservado.','Apotheosis cumulativa']
};
function makeFractal(n,theme){return fractal.map((name,i)=>({id:`g${n}_${i+1}`,name,desc:`${name} aplicada ao eixo deste Grau: ${theme}`,index:i,kind:i===9?'gate':'stage'}));}
const degrees=Array.from({length:33},(_,i)=>{const n=i+1,order=n<=11?'ARBOR VITAE':n<=22?'ARBOR MORTIS':'ARBOR DRACONIS',reserved=n>=23&&n<=32,p=profiles[n];const name=reserved?`Grau ${ROMAN[n]} · reservado`:(p?p[0]:`Grau ${ROMAN[n]}`),theme=reserved?'Conteúdo interno reservado. A versão pública preserva apenas a travessia lúdica da Arbor Draconis.':(p?p[1]:'Conteúdo em construção controlada.'),operation=reserved?'Operação interna não divulgada.':(p?p[2]:'Operação em construção.');return {number:n,roman:ROMAN[n],name,order,theme,operation,public:!reserved,provisional:n===22,steps:n===1?peregrinus:makeFractal(n,theme)}});

window.HarunCanonicalProgression=Object.freeze({version:'4.4.0',pathVersion:3,preStudentName:'INGRESSUS',ingressusRite:'ACTUS INGRESSUS',gameIngressusAdaptation:true,institutionalCurriculumReplica:false,studentIsDegree:false,studentMinimumDays:99,studentCycles:9,firstDegree:'Peregrinus Ignis',lastDegree:'Ipsissimus',publicThirdOrderReserved:true,ingressus,student,degrees,ludic:true,institutionalWrite:false});

function migratePath(meta){let p=meta.path;if(!p||typeof p!=='object')p=meta.path={phase:'ingressus',ingressusStage:0,studentStage:0,degree:1,degreeStage:0,completedDegrees:[]};if(!Array.isArray(p.completedDegrees))p.completedDegrees=[];if(meta.pathVersion!==3){if(meta.pathVersion===2&&p.phase==='ingressus')p.ingressusStage=Math.min(15,Math.floor((p.ingressusStage||0)*16/10));p.ingressusStage=Math.max(0,Math.min(16,p.ingressusStage||0));p.studentStage=Math.max(0,Math.min(15,p.studentStage||0));p.degree=Math.max(1,Math.min(33,p.degree||1));p.degreeStage=Math.max(0,p.degreeStage||0);meta.pathVersion=3}return p}
function persist(meta){try{localStorage.setItem(D.metaKey,JSON.stringify(meta))}catch(e){}}
function phaseTitle(p){if(p.phase==='ingressus')return 'INGRESSUS · CIDADELA';if(p.phase==='student')return 'ESTUDANTE · 99 DIAS';if(p.phase==='degrees'){const g=degrees[p.degree-1];return g.public?`GRAU ${g.roman} · ${g.name}`:`GRAU ${g.roman} · ARBOR DRACONIS`}return 'APOTHEOSIS'}
function phaseCopy(p){if(p.phase==='ingressus')return 'Os 16 mapas atuais formam o INGRESSUS lúdico de Hārūn. A Câmara final é o ACTUS INGRESSUS do jogo; depois começa a etapa Estudante.';if(p.phase==='student')return 'Etapa preparatória de 99 dias: 3 Períodos de 33, XI·1–XI·9, provas, Gate de Regência, Dossiê e Exame Individual. Estudante não é Grau.';if(p.phase==='degrees'){const g=degrees[p.degree-1];return g.public?`${g.order} · ${g.theme} · Operação: ${g.operation}`:`${g.order} · conteúdo institucional reservado. O jogo preserva apenas a estrutura lúdica da travessia.`}return 'XXXIII Graus atravessados no jogo. Apotheosis permanece processo cumulativo, não um fim metafísico.'}
function currentNodes(p){if(p.phase==='ingressus')return ingressus;if(p.phase==='student')return student;if(p.phase==='degrees')return degrees[p.degree-1].steps;return []}
function currentIndex(p){return p.phase==='ingressus'?p.ingressusStage:p.phase==='student'?p.studentStage:p.phase==='degrees'?p.degreeStage:0}
function actFor(p,idx){if(p.phase==='ingressus')return 1+Math.min(4,Math.floor(idx/4));if(p.phase==='student')return 1+(Math.floor(idx/3)%5);if(p.phase==='degrees'){if(p.degree<=11)return 1+((p.degree+idx)%3);if(p.degree<=22)return 3+((p.degree+idx)%3);return 5}return 1}
function degreeTooltip(g){return g.public?`${g.roman} · ${g.name}`:`${g.roman} · reservado`}
function timeline(p){const degreeChips=degrees.map(g=>{const done=p.completedDegrees.includes(g.number),on=p.phase==='degrees'&&p.degree===g.number,lock=p.phase!=='apotheosis'&&!done&&!on;return `<i class="prog-degree ${done?'done':''} ${on?'on':''} ${lock?'locked':''}" title="${degreeTooltip(g)}">${g.roman}</i>`}).join('');return `<div class="prog-timeline"><span class="${p.phase==='ingressus'?'on':''}">INGRESSUS</span><span class="${p.phase==='student'?'on':''}">ESTUDANTE</span><div class="prog-degrees">${degreeChips}</div></div>`}
function render(){const st=Core.getState(),meta=st.meta||{},p=migratePath(meta);persist(meta);if(st.state!=='menu')return;const nodes=currentNodes(p),idx=currentIndex(p),degree=p.phase==='degrees'?degrees[p.degree-1]:null,reserved=degree&&!degree.public,header=`<section class="prog-header ${reserved?'reserved':''}"><small>TRILHA INICIÁTICA · JOGO</small><h3>${phaseTitle(p)}</h3><p>${phaseCopy(p)}</p>${timeline(p)}</section>`;if(!nodes.length){campaign.innerHTML=header+`<div class="prog-finale"><b>XXXIII · IPSISSIMUS</b><p>Fim da progressão desta campanha. A conquista é lúdica e não concede Grau institucional.</p></div>`;return}campaign.innerHTML=header+`<div class="v4-stage-map prog-map">${nodes.map((n,i)=>{const done=i<idx,on=i===idx,locked=i>idx,sub=p.phase==='ingressus'?`INGRESSUS · ${n.subtitle||''}`:p.phase==='student'?'ESTUDANTE':`${degree.order} · ${degree.roman}`;return `<button class="v4-stage prog-stage ${done?'done':''} ${on?'current':''} ${locked?'locked':''} ${(n.kind==='gate'||n.kind==='rite')?'boss':''}" data-v4-stage="${n.id}" data-prog-index="${i}" ${locked||done?'disabled':''}><strong>${String(i+1).padStart(2,'0')} · ${n.name}</strong><small>${sub}</small><p>${n.desc||''}</p><span>${done?'CONCLUÍDO':on?'ENTRAR':'SELADO'}</span></button>`}).join('')}</div>`;campaign.querySelectorAll('[data-prog-index]:not([disabled])').forEach(b=>b.onclick=()=>beginNode(+b.dataset.progIndex))}
function showStartChoice(context){const box=$('#v4Glory'),choices=$('#v4GloryChoices');if(!box||!choices){startNode(context,'glory_thunder');return}const opts=[['glory_thunder','Raio','ϟ'],['glory_poison','Veneno','☣'],['glory_meteor','Meteoro','☄']];choices.innerHTML=opts.map(o=>`<button class="v4-choice rare" data-prog-glory="${o[0]}"><b>${o[1]}</b><i>${o[2]}</i><p>Manifestação inicial desta travessia.</p><small>GLÓRIA</small></button>`).join('');box.hidden=false;choices.querySelectorAll('[data-prog-glory]').forEach(b=>b.onclick=()=>{box.hidden=true;startNode(context,b.dataset.progGlory)})}
function beginNode(index){const st=Core.getState(),meta=st.meta,p=migratePath(meta),nodes=currentNodes(p);if(index!==currentIndex(p)||!nodes[index])return;showStartChoice({phase:p.phase,index,degree:p.degree||0,node:nodes[index],act:actFor(p,index)})}
if(quick)quick.onclick=()=>beginNode(currentIndex(migratePath(Core.getState().meta)));
function startNode(context,glory){Core.startRun(context.act);setTimeout(()=>{const st=Core.getState(),r=st.run;if(!r)return;r.progressionContext=context;r.skills[glory]=Math.max(1,r.skills[glory]||0);r.waveDuration=7.2;r._progressionBossSeen=false;r._progressionComplete=false;r._progressionCompleteAt=0;const story=$('#story');if(story)story.textContent=`${phaseTitle(migratePath(st.meta))} · ${context.node.name}`},30)}
function reward(meta,ctx,degreeCompleted=false){let gain=ctx.phase==='ingressus'?3+Math.floor(ctx.index/4):ctx.phase==='student'?6:8+(ctx.degree||1)*2;if(degreeCompleted)gain+=15+(ctx.degree||1)*3;meta.essence=(meta.essence||0)+gain;meta.pathHistory=Array.isArray(meta.pathHistory)?meta.pathHistory:[];meta.pathHistory.push({phase:ctx.phase,degree:ctx.degree||0,node:ctx.node&&ctx.node.id||'',reward:gain,at:Date.now()});if(meta.pathHistory.length>240)meta.pathHistory=meta.pathHistory.slice(-240);return gain}
function advance(meta,ctx){const p=migratePath(meta);if(ctx.phase!==p.phase)return 0;let degreeCompleted=false;if(p.phase==='ingressus'){p.ingressusStage++;if(p.ingressusStage>=ingressus.length){p.phase='student';p.ingressusStage=ingressus.length;p.studentStage=0}}else if(p.phase==='student'){p.studentStage++;if(p.studentStage>=student.length){p.phase='degrees';p.studentStage=student.length;p.degree=1;p.degreeStage=0}}else if(p.phase==='degrees'){const g=degrees[p.degree-1];p.degreeStage++;if(p.degreeStage>=g.steps.length){degreeCompleted=true;if(!p.completedDegrees.includes(g.number))p.completedDegrees.push(g.number);meta.bestDegree=Math.max(meta.bestDegree||0,g.number);if(g.number>=33){p.phase='apotheosis';p.degreeStage=0;meta.victories=(meta.victories||0)+1}else{p.degree=g.number+1;p.degreeStage=0}}}const gain=reward(meta,ctx,degreeCompleted);persist(meta);return gain}
function qaSetPath(next){if(!debugMode)return;const meta=Core.getState().meta;meta.path=Object.assign({phase:'ingressus',ingressusStage:0,studentStage:0,degree:1,degreeStage:0,completedDegrees:[]},next||{});meta.pathVersion=3;persist(meta);Core.showMenu('campaign');lastSig=''}
function qaAdvance(){if(!debugMode)return;const meta=Core.getState().meta,p=migratePath(meta),nodes=currentNodes(p),idx=currentIndex(p);if(nodes[idx])advance(meta,{phase:p.phase,degree:p.degree,index:idx,node:nodes[idx]});Core.showMenu('campaign');lastSig=''}
window.HarunProgressionDebug=Object.freeze({snapshot:()=>{const st=Core.getState(),p=migratePath(st.meta);return JSON.parse(JSON.stringify({path:p,phaseTitle:phaseTitle(p),nodes:currentNodes(p),degrees}));},setPath:qaSetPath,advanceCurrentForQA:qaAdvance});
let lastSig='';function loop(){const st=Core.getState(),meta=st.meta||{},p=migratePath(meta),r=st.run;if(st.state==='run'&&r&&r.progressionContext&&!r._progressionComplete){if(r.boss)r._progressionBossSeen=true;if(r._progressionBossSeen&&!r.boss){if(!r._progressionCompleteAt)r._progressionCompleteAt=performance.now()+240;if(performance.now()>=r._progressionCompleteAt){r._progressionComplete=true;const gain=advance(meta,r.progressionContext),toast=$('#v4Toast');if(toast){const c=r.progressionContext;toast.textContent=c.phase==='ingressus'&&c.node.id==='actus_ingressus_chamber'?`ACTUS INGRESSUS CONCLUÍDO · ESTUDANTE DESBLOQUEADO · +${gain} ESSÊNCIA`:c.phase==='student'&&c.node.id==='exame'?`ESTUDANTE CONCLUÍDO · PEREGRINUS IGNIS DESBLOQUEADO · +${gain} ESSÊNCIA`:`ETAPA CONCLUÍDA · +${gain} ESSÊNCIA`;toast.hidden=false;setTimeout(()=>toast.hidden=true,1800)}setTimeout(()=>Core.showMenu('campaign'),650)}}}if(st.state==='menu'){const sig=JSON.stringify(p);if(sig!==lastSig||!campaign.querySelector('.prog-header')){lastSig=sig;render()}}requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();