(function(){
'use strict';
const Core=window.HarunSurvivorDebug,D=window.HarunSurvivorData;if(!Core||!D)throw new Error('Survivor V5 progression requires core');
const $=s=>document.querySelector(s),campaign=$('#campaign'),quick=$('#startQuick');
const ROMAN=['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI','XXII','XXIII','XXIV','XXV','XXVI','XXVII','XXVIII','XXIX','XXX','XXXI','XXXII','XXXIII'];
const fractal=['Caverna','Revelação','Ruptura','Limiar','Travessia','Provação','Reintegração','Encarnar','Obra','Passagem'];
const degreeNames={1:'Peregrinus Ignis',2:'Neophyte',3:'Architectus',4:'Practicus',5:'Philosophus',6:'Dominus Liminis',7:'Adeptus Minor',8:'Clavis Potestatis',9:'Adeptus Exemptus',10:'Magister Templi',11:'Magus',12:'Lilith',13:'Gamaliel',14:'Samael',15:'A’arab Zaraq',16:'Thagirion',17:'Golachab',18:'Gha’agsheblah',19:'Satariel',20:'Ghagiel',21:'Thaumiel',22:'Adamas Ater',33:'Ipsissimus'};

const prelude=[
 {id:'o_olho',name:'O OLHO',subtitle:'PERCEPÇÃO',desc:'Perceber antes de concluir.',bossId:'blind_observer',boss:'OBSERVADOR CEGO'},
 {id:'a_chama',name:'A CHAMA',subtitle:'REGÊNCIA',desc:'Governar o impulso em vez de ser governado por ele.',bossId:'impulse_archon',boss:'ARCONTE DO IMPULSO'},
 {id:'a_fundacao',name:'A FUNDAÇÃO',subtitle:'ESTRUTURA',desc:'Erguer limite, corpo e sustentação.',bossId:'inert_stone_guardian',boss:'GUARDIÃO DA PEDRA INERTE'},
 {id:'ritual_inicial',name:'RITUAL INICIAL BÁSICO',subtitle:'ADMISSÃO',desc:'O primeiro selo abre a entrada na SOCIETAS.',kind:'ritual'}
];
const ingressus=[
 {id:'heru_pa_khered',name:'PERGAMINHO I · HERU-PA-KHERED',subtitle:'HÓRUS CRIANÇA',desc:'Primeira forma horiana do Ingressus.',boss:'GUARDIÃO DO NASCIMENTO',form:'Heru-pa-khered'},
 {id:'heru_sa_aset',name:'PERGAMINHO II · HERU-SA-ASET',subtitle:'HÓRUS FILHO DE ÍSIS',desc:'A forma que aprende filiação, direção e memória.',boss:'GUARDIÃO DA FILIAÇÃO',form:'Heru-sa-Aset'},
 {id:'heru_behdeti',name:'PERGAMINHO III · HERU-BEHDETI',subtitle:'HÓRUS DE BEHDET',desc:'A forma solar alada que assume direção e travessia.',boss:'GUARDIÃO DO DISCO ALADO',form:'Heru-Behdeti'},
 {id:'actus_ingressus',name:'RITUAL DO ACTUS INGRESSUS',subtitle:'SELO DO INGRESSUS',desc:'Três Pergaminhos são reunidos e o Ingressus é selado.',kind:'ritual'}
];
const studentNames=[
 ['a_eleicao','PERGAMINHO I · A ELEIÇÃO','Autoeleição e autoria.'],['a_balanca','PERGAMINHO II · A BALANÇA','Autorresponsabilidade, custo e consequência.'],['a_vontade','PERGAMINHO III · A VONTADE','Verdadeira Vontade e direção estável.'],['o_carater','PERGAMINHO IV · O CARÁTER','Coerência entre palavra e ato.'],['a_disciplina','PERGAMINHO V · A DISCIPLINA','Ritmo e constância.'],['a_clareza','PERGAMINHO VI · A CLAREZA','Discriminação e leitura causal.'],['a_transmutacao','PERGAMINHO VII · A TRANSMUTAÇÃO','Converter conflito em recurso.'],['o_corpo','PERGAMINHO VIII · O CORPO','Corpo, energia e sustentação.'],['a_obra','PERGAMINHO IX · A OBRA','Vontade convertida em construção.'],['a_fortuna','PERGAMINHO X · A FORTUNA','Risco, oportunidade e recursos.'],['a_influencia','PERGAMINHO XI · A INFLUÊNCIA','Voz, presença e contágio social.'],['o_legado','PERGAMINHO XII · O LEGADO','Memória, continuidade e nome.']
];
const student=studentNames.map((x,i)=>({id:x[0],name:x[1],subtitle:'ESTUDANTE',desc:x[2],scroll:i+1,boss:`PROVA · ${x[1].split(' · ')[1]}`}));
student.push({id:'ritual_estudante',name:'RITUAL DE PASSAGEM · PEREGRINUS IGNIS',subtitle:'FIM DA ETAPA ESTUDANTE',desc:'Os doze Pergaminhos são reunidos antes do Grau I.',kind:'ritual'});
const peregrinus=['Autoeleição','Autorresponsabilidade','Verdadeira Vontade','Caráter','Disciplina','Clareza','Transmutação','Corpo e Energia','Obra','Fortuna','Influência','Legado','Forja do Pergaminho Pessoal'].map((name,i)=>({id:`g1_${i+1}`,name,desc:`Grau I · ${name}`,index:i,kind:i===12?'gate':'scroll'}));
const degrees=Array.from({length:33},(_,i)=>{const n=i+1,reserved=n>=23&&n<=32,name=reserved?`Grau ${ROMAN[n]} · reservado`:(degreeNames[n]||`Grau ${ROMAN[n]}`),order=n<=11?'ARBOR VITAE':n<=22?'ARBOR MORTIS':'ARBOR DRACONIS';return{number:n,roman:ROMAN[n],name,order,public:!reserved,theme:reserved?'Conteúdo institucional reservado; somente travessia lúdica pública.':`Travessia lúdica do ${name}.`,operation:reserved?'Operação interna não divulgada.':`Rito de passagem do ${name}.`,steps:n===1?peregrinus:fractal.map((s,j)=>({id:`g${n}_${j+1}`,name:s,desc:`${s} · ${name}`,index:j,kind:j===9?'gate':'stage'}))}});
window.HarunCanonicalProgression=Object.freeze({version:'5.0.0',pathVersion:5,preStudentName:'INGRESSUS',preIngressus:true,ingressusRite:'ACTUS INGRESSUS',studentIsDegree:false,studentScrolls:12,ingressusScrolls:3,firstDegree:'Peregrinus Ignis',lastDegree:'Ipsissimus',publicThirdOrderReserved:true,prelude,ingressus,student,degrees,ludic:true,institutionalWrite:false});

function path(meta){let p=meta.v5Path;if(!p||typeof p!=='object')p=meta.v5Path={phase:'prelude',index:0,degree:1,degreeIndex:0,completedDegrees:[]};if(!Array.isArray(p.completedDegrees))p.completedDegrees=[];return p}
function save(meta){try{localStorage.setItem(D.metaKey,JSON.stringify(meta))}catch(_){}}
function nodes(p){if(p.phase==='prelude')return prelude;if(p.phase==='ingressus')return ingressus;if(p.phase==='student')return student;if(p.phase==='degrees')return degrees[p.degree-1].steps;return[]}
function idx(p){return p.phase==='degrees'?p.degreeIndex:p.index}
function title(p){if(p.phase==='prelude')return 'PRÉ-INGRESSUS · DESPERTAR';if(p.phase==='ingressus')return 'INGRESSUS · TRÊS FORMAS DE HÓRUS';if(p.phase==='student')return 'ESTUDANTE · XII PERGAMINHOS';if(p.phase==='degrees'){const g=degrees[p.degree-1];return g.public?`GRAU ${g.roman} · ${g.name}`:`GRAU ${g.roman} · ARBOR DRACONIS`}return 'APOTHEOSIS'}
function copy(p){if(p.phase==='prelude')return 'O Olho, A Chama e A Fundação precedem a admissão. Ao fim, acontece o Ritual Inicial Básico.';if(p.phase==='ingressus')return 'Três Pergaminhos, três formas horianas: Heru-pa-khered → Heru-sa-Aset → Heru-Behdeti. O ACTUS INGRESSUS sela a travessia.';if(p.phase==='student')return 'Doze Pergaminhos formativos. Estudante não é Grau.';if(p.phase==='degrees'){const g=degrees[p.degree-1];return g.public?`${g.order} · ${g.theme}`:`${g.order} · conteúdo institucional reservado; somente estrutura lúdica visível.`}return 'XXXIII atravessado no jogo; nenhuma conquista lúdica concede Grau institucional.'}
function actFor(p,i){if(p.phase==='prelude')return i+1;if(p.phase==='ingressus')return Math.min(5,2+i);if(p.phase==='student')return 1+(i%5);if(p.phase==='degrees')return p.degree<=11?1+((p.degree+i)%3):p.degree<=22?3+((p.degree+i)%3):5;return 1}
function degreeChips(p){return degrees.map(g=>{const done=p.completedDegrees.includes(g.number),on=p.phase==='degrees'&&p.degree===g.number;return `<i class="prog-degree ${done?'done':''} ${on?'on':''}" title="${g.public?g.name:'reservado'}">${g.roman}</i>`}).join('')}
function render(){const st=Core.getState();if(st.state!=='menu')return;const meta=st.meta,p=path(meta),list=nodes(p),at=idx(p);save(meta);const head=`<section class="prog-header v5-prog"><small>TRILHA V5 · JOGO</small><h3>${title(p)}</h3><p>${copy(p)}</p><div class="prog-timeline"><span class="${p.phase==='prelude'?'on':''}">PRÉ</span><span class="${p.phase==='ingressus'?'on':''}">INGRESSUS</span><span class="${p.phase==='student'?'on':''}">ESTUDANTE</span><div class="prog-degrees">${degreeChips(p)}</div></div></section>`;if(!list.length){campaign.innerHTML=head+`<div class="prog-finale"><b>XXXIII · IPSISSIMUS</b><p>Travessia lúdica concluída.</p></div>`;return}campaign.innerHTML=head+`<div class="v4-stage-map prog-map">${list.map((n,i)=>{const done=i<at,on=i===at,locked=i>at,rit=n.kind==='ritual';return `<button class="v4-stage prog-stage ${done?'done':''} ${on?'current':''} ${locked?'locked':''} ${rit?'boss':''}" data-v5-index="${i}" ${done||locked?'disabled':''}><strong>${String(i+1).padStart(2,'0')} · ${n.name}</strong><small>${n.subtitle||p.phase.toUpperCase()}</small><p>${n.desc||''}</p><span>${done?'CONCLUÍDO':on?(rit?'REALIZAR RITUAL':'ENTRAR'):'SELADO'}</span></button>`}).join('')}</div>`;campaign.querySelectorAll('[data-v5-index]:not([disabled])').forEach(b=>b.onclick=()=>begin(+b.dataset.v5Index))}
function ritualOverlay(node,onSeal){let el=$('#v5Ritual');if(!el){el=document.createElement('section');el.id='v5Ritual';el.className='v5-overlay';document.querySelector('.frame').appendChild(el)}el.innerHTML=`<article class="v5-ritual-card"><small>RITO DE PASSAGEM</small><h2>${node.name}</h2><p>${node.desc||'A travessia é selada antes da próxima passagem.'}</p><div class="v5-sigil">✦</div><button id="v5Seal">SELAR E CONTINUAR</button></article>`;el.hidden=false;window.MUNDUSAudio?.setState('ritual',{intensity:.45});window.MUNDUSAudio?.sfx('ritual');$('#v5Seal').onclick=()=>{el.hidden=true;window.MUNDUSAudio?.sfx('ritual_seal');onSeal()}}
function advance(meta){const p=path(meta);if(p.phase==='prelude'){p.index++;if(p.index>=prelude.length){p.phase='ingressus';p.index=0}}else if(p.phase==='ingressus'){p.index++;if(p.index>=ingressus.length){p.phase='student';p.index=0}}else if(p.phase==='student'){p.index++;if(p.index>=student.length){p.phase='degrees';p.index=0;p.degree=1;p.degreeIndex=0}}else if(p.phase==='degrees'){const g=degrees[p.degree-1];p.degreeIndex++;if(p.degreeIndex>=g.steps.length){if(!p.completedDegrees.includes(g.number))p.completedDegrees.push(g.number);if(g.number>=33){p.phase='apotheosis';p.degreeIndex=0}else{p.degree++;p.degreeIndex=0}}}save(meta)}
function contextFor(p,i,n){return{phase:p.phase,index:i,degree:p.degree||0,node:n,act:actFor(p,i),v5:true}}
function begin(i){const st=Core.getState(),p=path(st.meta),list=nodes(p),n=list[i];if(!n||i!==idx(p))return;if(n.kind==='ritual'){ritualOverlay(n,()=>{advance(st.meta);Core.showMenu('campaign');last='';render()});return}const box=$('#v4Glory'),choices=$('#v4GloryChoices'),ctx=contextFor(p,i,n);const opts=[['glory_thunder','Raio','ϟ'],['glory_poison','Veneno','☣'],['glory_meteor','Meteoro','☄']];choices.innerHTML=opts.map(o=>`<button class="v4-choice rare" data-v5-glory="${o[0]}"><b>${o[1]}</b><i>${o[2]}</i><p>Manifestação inicial desta travessia.</p><small>GLÓRIA</small></button>`).join('');box.hidden=false;choices.querySelectorAll('[data-v5-glory]').forEach(b=>b.onclick=()=>{box.hidden=true;Core.startRun(ctx.act);setTimeout(()=>{const s=Core.getState(),r=s.run;if(!r)return;r.v5Context=ctx;r.progressionContext=ctx;r.skills[b.dataset.v5Glory]=1;r._v5BossSeen=false;r._v5Sealed=false;r.waveDuration=7.2;const story=$('#story');if(story)story.textContent=`${title(path(s.meta))} · ${n.name}`},30)})}
if(quick)quick.onclick=()=>{const st=Core.getState(),p=path(st.meta);begin(idx(p))};
function sealCombat(meta,ctx){const node=ctx.node||{};const needsSeal=ctx.phase==='ingressus'||ctx.phase==='student'||ctx.phase==='degrees';const done=()=>{advance(meta);Core.showMenu('campaign');last=''};if(needsSeal)ritualOverlay({name:`RITO DE SELAMENTO · ${node.name}`,desc:`A experiência de ${node.name} é registrada no Livro Negro e selada antes da próxima passagem.`},done);else done()}
let last='';function loop(){const st=Core.getState(),meta=st.meta||{},p=path(meta),r=st.run;if(st.state==='run'&&r&&r.v5Context&&!r._v5Sealed){if(r.boss)r._v5BossSeen=true;if(r._v5BossSeen&&!r.boss){r._v5Sealed=true;setTimeout(()=>sealCombat(meta,r.v5Context),320)}}if(st.state==='menu'){const sig=JSON.stringify(p);if(sig!==last||!campaign.querySelector('.v5-prog')){last=sig;render()}}requestAnimationFrame(loop)}
window.HarunV5Progression=Object.freeze({version:'5.0.0',snapshot:()=>{const st=Core.getState(),p=path(st.meta);return JSON.parse(JSON.stringify({path:p,title:title(p),nodes:nodes(p),degrees}))},setPathForQA(next){const m=Core.getState().meta;m.v5Path=Object.assign({phase:'prelude',index:0,degree:1,degreeIndex:0,completedDegrees:[]},next||{});save(m);Core.showMenu('campaign');last=''},advanceForQA(){const m=Core.getState().meta;advance(m);Core.showMenu('campaign');last=''}});
requestAnimationFrame(loop);
})();