(function(){
'use strict';
const Core=window.HarunSurvivorDebug,P=window.HarunCanonicalProgression,D=window.HarunSurvivorData;if(!Core||!P||!D)return;
const $=s=>document.querySelector(s),frame=$('.frame');let activeSig='',lastBoss=null,last=performance.now();
const bosses={
 o_olho:'OBSERVADOR CEGO',a_chama:'ARCONTE DO IMPULSO',a_fundacao:'GUARDIÃO DA PEDRA INERTE',
 heru_pa_khered:'GUARDIÃO DO NASCIMENTO',heru_sa_aset:'GUARDIÃO DA FILIAÇÃO',heru_behdeti:'GUARDIÃO DO DISCO ALADO'
};
function systems(meta){meta.v5Systems=meta.v5Systems||{tarotSeen:[],tarotOwned:[],familiars:[],beings:[],daimons:[],pacts:[],relics:[],rituals:[],bestiary:[]};meta.v5Systems.rituals=Array.isArray(meta.v5Systems.rituals)?meta.v5Systems.rituals:[];return meta.v5Systems}
function save(meta){try{localStorage.setItem(D.metaKey,JSON.stringify(meta))}catch(_){}}
function sig(ctx){return ctx?`${ctx.phase}:${ctx.degree||0}:${ctx.index}:${ctx.node?.id||''}`:''}
function degree(ctx){return ctx?.phase==='degrees'?P.degrees[(ctx.degree||1)-1]:null}
function key(ctx){const g=degree(ctx);if(g)return g.number<=11?'vitae':g.number<=22?'mortis':'draconis';return ctx?.phase||'prelude'}
function difficulty(ctx){const g=degree(ctx);if(!g){if(ctx?.phase==='prelude')return 1+.05*(ctx.index||0);if(ctx?.phase==='ingressus')return 1.18+.06*(ctx.index||0);if(ctx?.phase==='student')return 1.35+.025*(ctx.index||0);return 1}if(g.number<=11)return 1.55+g.number*.035;if(g.number<=22)return 2.0+(g.number-11)*.055;return 2.65+(g.number-22)*.07}
function badge(ctx){let b=$('#v5PhaseBadge');if(!b){b=document.createElement('div');b.id='v5PhaseBadge';frame.appendChild(b)}const g=degree(ctx);if(g)b.innerHTML=`<small>${g.order}</small><b>GRAU ${g.roman}</b><span>${g.public?g.name:'CONTEÚDO RESERVADO'}</span>`;else b.innerHTML=`<small>${ctx.phase==='prelude'?'ANTES DO INGRESSUS':ctx.phase==='ingressus'?'INGRESSUS · SOCIETAS':'ETAPA FORMATIVA'}</small><b>${ctx.node?.name||ctx.phase}</b><span>${ctx.node?.subtitle||''}</span>`;b.hidden=false}
function applyRun(run,ctx){const k=key(ctx),mul=difficulty(ctx);run.v5Runtime={sig:sig(ctx),key:k,difficulty:mul};frame.dataset.v5Phase=k;badge(ctx);const p=run.player;if(ctx.phase==='prelude'){p.speed*=1.04;p.damage*=1.02}else if(ctx.phase==='ingressus'){p.speed*=1.05;p.crit+=.015}else if(ctx.phase==='student'){p.pickup+=8;p.crit+=.02}else if(ctx.phase==='degrees'){const g=degree(ctx),n=g.number;p.damage*=1+Math.min(.42,.06+n*.009);p.maxHp*=1+Math.min(.22,n*.005);p.hp=p.maxHp;if(k==='vitae'){p.pickup+=5+n;p.dodge+=.004*n}else if(k==='mortis'){p.crit+=.04+(n-11)*.003;p.speed+=Math.min(20,(n-11)*1.4)}else{p.damage*=1.1;p.dodge+=.02;p.fireRate=Math.max(.15,p.fireRate*.92)}}}
function scale(e,run){const rt=run.v5Runtime;if(!rt||e._v5Rt===rt.sig)return;e._v5Rt=rt.sig;const m=rt.difficulty;e.hp*=m;e.maxHp*=m;e.damage*=.94+m*.13;e.speed*=Math.min(1.28,.98+(m-1)*.06);if(rt.key==='mortis'){e.damage*=1.09;e.speed*=1.04}else if(rt.key==='draconis'){e.hp*=1.1;e.maxHp*=1.1;e.damage*=1.12}if(e.kind==='boss'){e.hp*=1.22;e.maxHp*=1.22}}
function bossName(run,ctx){if(!run.boss||run.boss===lastBoss)return;lastBoss=run.boss;const g=degree(ctx),id=ctx.node?.id;if(bosses[id])run.boss.name=bosses[id];else if(ctx.phase==='student')run.boss.name=`PROVA · ${String(ctx.node?.name||'ESTUDANTE').replace(/^PERGAMINHO [IVX]+ · /,'')}`;else if(g){run.boss.name=g.number===33?'LIMIAR · IPSISSIMUS':g.public?`PROVA · ${g.name.toUpperCase()}`:`GUARDIÃO · GRAU ${g.roman}`}if(ctx.node?.kind==='gate'){run.boss.hp*=1.16;run.boss.maxHp*=1.16}}
function recordRitual(name){const st=Core.getState(),sys=systems(st.meta);if(!sys.rituals.some(x=>x.name===name)){sys.rituals.push({name,at:Date.now()});save(st.meta)}}
window.addEventListener('click',e=>{if(e.target?.id==='v5Seal'){const name=$('#v5Ritual h2')?.textContent?.trim();if(name)recordRitual(name)}},true);
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;const st=Core.getState(),r=st.run;if(st.state==='run'&&r&&r.v5Context){const s=sig(r.v5Context);if(s!==activeSig){activeSig=s;lastBoss=null;applyRun(r,r.v5Context)}for(const e of r.enemies)scale(e,r);bossName(r,r.v5Context);if(r.v5Runtime?.key==='vitae'&&Math.floor(r.time)%9===0&&r._v5HealTick!==Math.floor(r.time/9)){r._v5HealTick=Math.floor(r.time/9);r.player.hp=Math.min(r.player.maxHp,r.player.hp+r.player.maxHp*.025)}}else if(st.state==='menu'){activeSig='';lastBoss=null;const b=$('#v5PhaseBadge');if(b)b.hidden=true;delete frame.dataset.v5Phase}requestAnimationFrame(loop)}
window.HarunV5Runtime=Object.freeze({version:'5.0.0',difficultyFor:ctx=>difficulty(ctx),active:()=>Core.getState().run?.v5Runtime?{...Core.getState().run.v5Runtime}:null,bosses:Object.freeze({...bosses})});requestAnimationFrame(loop);
})();