(function(){
'use strict';
const Core=window.HarunSurvivorDebug;if(!Core)throw new Error('V5 systems require Survivor core');
const $=s=>document.querySelector(s),frame=$('.frame');
const majors=['O Louco','O Mago','A Sacerdotisa','A Imperatriz','O Imperador','O Hierofante','Os Amantes','O Carro','Ajustamento','O Eremita','Fortuna','Luxúria','O Enforcado','Morte','Arte','O Diabo','A Torre','A Estrela','A Lua','O Sol','O Aeon','O Universo'];
const suitRanks={
 Paus:['Ás de Paus','Domínio','Virtude','Conclusão','Conflito','Vitória','Valor','Rapidez','Força','Opressão'],
 Copas:['Ás de Copas','Amor','Abundância','Luxo','Decepção','Prazer','Deboche','Indolência','Felicidade','Saciedade'],
 Espadas:['Ás de Espadas','Paz','Tristeza','Trégua','Derrota','Ciência','Futilidade','Interferência','Crueldade','Ruína'],
 Discos:['Ás de Discos','Mudança','Trabalhos','Poder','Preocupação','Sucesso','Fracasso','Prudência','Ganho','Riqueza']
};
const courts=['Cavaleiro','Rainha','Príncipe','Princesa'];
const tarot=[];
majors.forEach((name,i)=>tarot.push({id:`atu_${i}`,name,suit:'ATU',rank:i,icon:['○','☿','☾','♀','♂','♉','♊','♋','⚖','☿','☸','♌','▽','♏','⚗','♑','⚡','☆','☽','☉','◉','⊕'][i],effect:`ATU ${String(i).padStart(2,'0')} altera uma regra central da run.`}));
Object.entries(suitRanks).forEach(([suit,names],si)=>{names.forEach((name,i)=>tarot.push({id:`${suit.toLowerCase()}_${i+1}`,name,suit,rank:i+1,icon:['♨','♒','⚔','◈'][si],effect:`${suit}: manifestação ${i+1} com bônus próprio de ${['dano e cadência','vida e regeneração','crítico e penetração','fortuna e coleta'][si]}.`}));courts.forEach((court,i)=>tarot.push({id:`${suit.toLowerCase()}_court_${i}`,name:`${court} de ${suit}`,suit,rank:11+i,icon:['♨','♒','⚔','◈'][si],effect:`Corte de ${suit}: invoca uma presença de ${court.toLowerCase()} que modifica a build.`}))});
if(tarot.length!==78)throw new Error(`Tarot Thoth V5 inválido: ${tarot.length}`);

const familiars=[
 {id:'scarab',name:'Escaravelho de Khepri',effect:'Orbita Hārūn e lança pulsos solares.'},{id:'ibis',name:'Íbis de Thoth',effect:'Aumenta crítico e revela salas especiais.'},{id:'falcon',name:'Falcão de Hórus',effect:'Ataca o inimigo mais distante.'},{id:'serpent',name:'Serpente de Wadjet',effect:'Aplica veneno em contatos próximos.'},{id:'jackal',name:'Chacal do Limiar',effect:'Aumenta velocidade e coleta.'},{id:'beetle',name:'Besouro de Cinza',effect:'Bloqueia um projétil periodicamente.'},{id:'lotus',name:'Lótus Vivo',effect:'Regenera Sopro Vital lentamente.'},{id:'sphinx',name:'Esfinge Menor',effect:'Amplia dano contra elites e chefes.'},{id:'owl',name:'Coruja da Noite',effect:'Aumenta sorte e frequência de salas raras.'},{id:'lion',name:'Leão Solar',effect:'Cria rugido de dano em área.'},{id:'raven',name:'Corvo de Caim',effect:'Marca inimigos feridos para execução.'},{id:'moth',name:'Mariposa de Nuit',effect:'Aumenta esquiva e invulnerabilidade pós-dano.'}
];
const beings=[
 {id:'solar_seraph',name:'Ser Solar',effect:'Explosão temporária de dano e luz.'},{id:'lunar_watcher',name:'Vigia Lunar',effect:'Lentidão global por alguns segundos.'},{id:'keeper_gate',name:'Guardião do Portal',effect:'Escudo total breve.'},{id:'scribe',name:'Escriba Velado',effect:'Duplica a próxima recompensa.'},{id:'wanderer',name:'Peregrino de Cinza',effect:'Converte dano sofrido em poder temporário.'},{id:'herald',name:'Arauto de Behdet',effect:'Rajada de lâminas diagonais.'},{id:'silent_one',name:'O Silencioso',effect:'Congela projéteis inimigos.'},{id:'torch_bearer',name:'Portador da Chama',effect:'Incendeia toda a sala.'},{id:'mirror_being',name:'Ser do Espelho',effect:'Repete o último ataque especial.'},{id:'foundation_colossus',name:'Colosso da Fundação',effect:'Aumenta massa e resistência temporariamente.'},{id:'star_child',name:'Filho da Estrela',effect:'Aumenta XP e essência da sala.'},{id:'abyss_eye',name:'Olho do Abismo',effect:'Revela e danifica alvos ocultos.'}
];
const daimons=[
 {id:'daimon_horus',name:'Daimon Horiano',effect:'Dano, crítico e velocidade de ataque aumentam.'},{id:'daimon_thoth',name:'Daimon de Thoth',effect:'Cartas raras aparecem com mais frequência.'},{id:'daimon_phosphoros',name:'Daimon Phosphoros',effect:'Projéteis ganham fogo e explosão.'},{id:'daimon_cain',name:'Daimon de Caim',effect:'Execuções fortalecem a build até o fim da run.'},{id:'daimon_nuit',name:'Daimon de Nuit',effect:'Esquiva e mobilidade aumentam.'},{id:'daimon_belial',name:'Daimon de Belial',effect:'Grande dano em troca de Sopro Vital máximo.'},{id:'daimon_paimon',name:'Daimon de Paimon',effect:'Fortuna, drops e dano de familiares aumentam.'},{id:'daimon_serpent',name:'Daimon Serpentino',effect:'Veneno, ricochete e transmutação aumentam.'}
];
const pacts=[
 {id:'pact_flame',name:'Pacto da Chama',cost:'-15% Sopro Vital Máx.',effect:'+28% dano e fogo.'},{id:'pact_eye',name:'Pacto do Olho',cost:'-10% velocidade.',effect:'+18% crítico e revela mapa.'},{id:'pact_blood',name:'Pacto do Sangue',cost:'Dano recebido +15%.',effect:'Cura ao eliminar elites.'},{id:'pact_fortune',name:'Pacto da Fortuna',cost:'Chefes +18% vida.',effect:'Drops e essência +35%.'},{id:'pact_shadow',name:'Pacto da Sombra',cost:'Visibilidade reduzida.',effect:'Esquiva +20% e dano traseiro.'},{id:'pact_word',name:'Pacto do Verbo',cost:'Cadência inicial menor.',effect:'Ataques especiais muito mais fortes.'},{id:'pact_abyss',name:'Pacto do Abismo',cost:'Uma carta da build é selada.',effect:'Recebe duas novas cartas lendárias.'},{id:'pact_crown',name:'Pacto da Coroa',cost:'Sem cura passiva.',effect:'Familiars e Daimon causam dano dobrado.'}
];

function state(meta){if(!meta.v5Systems)meta.v5Systems={tarotSeen:[],tarotOwned:[],familiars:[],beings:[],daimons:[],pacts:[],relics:[],rituals:[],bestiary:[]};return meta.v5Systems}
function save(meta){try{localStorage.setItem(window.HarunSurvivorData.metaKey,JSON.stringify(meta))}catch(_){}}
function pause(on){const b=$('#pause'),st=Core.getState();if(st.state!=='run'||!b)return;if(on&&b.textContent!=='▶')b.click();if(!on&&b.textContent==='▶')b.click()}
function ensureChoice(){let el=$('#v5Choice');if(!el){el=document.createElement('section');el.id='v5Choice';el.className='v5-overlay';frame.appendChild(el)}return el}
function cardColor(c){return c.suit==='ATU'?'legend':c.suit==='Espadas'?'epic':'rare'}
function drawTarot(count=3){const st=Core.getState(),meta=st.meta,s=state(meta),owned=new Set(s.tarotSeen),pool=tarot.filter(c=>!owned.has(c.id));const chosen=[];while(pool.length&&chosen.length<count){const ix=Math.floor(Math.random()*pool.length);chosen.push(pool.splice(ix,1)[0])}if(chosen.length<count){s.tarotSeen=[];return drawTarot(count)}return chosen}
function applyTarot(c){const st=Core.getState(),r=st.run;if(!r)return;const p=r.player,major=c.suit==='ATU',rank=c.rank||1;if(major){const m=c.rank%7;if(m===0)p.damage*=1.16;else if(m===1)p.fireRate=Math.max(.16,p.fireRate*.88);else if(m===2){p.maxHp*=1.14;p.hp=p.maxHp}else if(m===3)p.speed*=1.15;else if(m===4){p.crit+=.08;p.pierce++}else if(m===5){p.dodge+=.07;p.pickup+=18}else{p.orbits=Math.min(7,p.orbits+2);p.ric++}}else if(c.suit==='Paus'){p.damage*=1.035+rank*.006;p.fireRate=Math.max(.16,p.fireRate*(.99-rank*.004))}else if(c.suit==='Copas'){p.maxHp*=1.025+rank*.004;p.hp=Math.min(p.maxHp,p.hp+1+rank*.12)}else if(c.suit==='Espadas'){p.crit+=.012+rank*.003;if(rank%3===0)p.pierce++}else{p.pickup+=3+rank;p.dodge+=.004+rank*.001}if(c.rank>=11){p.damage*=1.05;p.speed*=1.04}}
function chooseTarot(cards=drawTarot()){const st=Core.getState();if(st.state!=='run'||!st.run)return;const el=ensureChoice();pause(true);el.innerHTML=`<article class="v5-choice-shell"><small>ARCANA · THOTH</small><h2>ESCOLHA UMA CARTA</h2><p>A escolhida entra na run. As outras desaparecem.</p><div class="v5-card-grid">${cards.map(c=>`<button class="v5-tarot ${cardColor(c)}" data-tarot="${c.id}"><span>${c.suit}</span><i>${c.icon}</i><b>${c.name}</b><small>${c.effect}</small></button>`).join('')}</div></article>`;el.hidden=false;el.querySelectorAll('[data-tarot]').forEach(b=>b.onclick=()=>{const c=cards.find(x=>x.id===b.dataset.tarot),meta=Core.getState().meta,s=state(meta);s.tarotSeen.push(c.id);if(!s.tarotOwned.includes(c.id))s.tarotOwned.push(c.id);applyTarot(c);save(meta);window.MUNDUSAudio?.sfx('arcana');el.innerHTML='';el.hidden=true;pause(false);window.dispatchEvent(new CustomEvent('mundus:v5:tarot',{detail:c}))})}
function gain(kind,item){const st=Core.getState(),s=state(st.meta),arr=s[kind];if(!arr.includes(item.id))arr.push(item.id);const r=st.run;if(r){if(kind==='familiars'){r.player.damage*=1.05;r.player.pickup+=10}if(kind==='beings'){r.player.hp=Math.min(r.player.maxHp,r.player.hp+2);r.player.crit+=.02}if(kind==='daimons'){r.player.damage*=1.16;r.player.crit+=.05;r.player.fireRate=Math.max(.16,r.player.fireRate*.9)}if(kind==='pacts'){if(item.id==='pact_flame'){r.player.maxHp*=.85;r.player.hp=Math.min(r.player.hp,r.player.maxHp);r.player.damage*=1.28;r.player.burn+=.3}else if(item.id==='pact_eye'){r.player.speed*=.9;r.player.crit+=.18}else if(item.id==='pact_fortune'){r.player.pickup+=45;r.player.crit+=.04}else{r.player.damage*=1.1;r.player.dodge+=.03}}}save(st.meta);window.MUNDUSAudio?.sfx(kind==='pacts'?'ritual':'pickup');window.dispatchEvent(new CustomEvent('mundus:v5:gain',{detail:{kind,item}}));return item}
function offerCatalog(kind,catalog,title){const st=Core.getState();if(st.state!=='run')return;const s=state(st.meta),owned=new Set(s[kind]||[]),pool=catalog.filter(x=>!owned.has(x.id)),items=(pool.length?pool:catalog).sort(()=>Math.random()-.5).slice(0,2),el=ensureChoice();pause(true);el.innerHTML=`<article class="v5-choice-shell"><small>${title}</small><h2>ESCOLHA UMA MANIFESTAÇÃO</h2><div class="v5-card-grid two">${items.map(x=>`<button class="v5-system-card" data-system="${x.id}"><i>◇</i><b>${x.name}</b><small>${x.effect}${x.cost?`<br><em>${x.cost}</em>`:''}</small></button>`).join('')}</div></article>`;el.hidden=false;el.querySelectorAll('[data-system]').forEach(b=>b.onclick=()=>{const item=items.find(x=>x.id===b.dataset.system);gain(kind,item);el.hidden=true;el.innerHTML='';pause(false)})}

let lastRun=null,lastLevel=0,lastWave=0;function loop(){const st=Core.getState(),r=st.run;if(st.state==='run'&&r){state(st.meta);if(r!==lastRun){lastRun=r;lastLevel=r.level;lastWave=r.wave;r._v5Systems=true}if(r.level>lastLevel){lastLevel=r.level;if(r.level%4===0&&!document.querySelector('#v5Choice:not([hidden])'))setTimeout(()=>chooseTarot(),80)}if(r.wave!==lastWave){lastWave=r.wave;if(r.wave>1&&r.wave%13===0)setTimeout(()=>offerCatalog('familiars',familiars,'FAMILIAR'),120);else if(r.wave>1&&r.wave%17===0)setTimeout(()=>offerCatalog('beings',beings,'SER'),120);else if(r.wave>1&&r.wave%23===0)setTimeout(()=>offerCatalog('daimons',daimons,'DAIMON'),120);else if(r.wave>1&&r.wave%19===0)setTimeout(()=>offerCatalog('pacts',pacts,'PACTO'),120)}}else if(st.state==='menu'){lastRun=null;lastLevel=0;lastWave=0}requestAnimationFrame(loop)}
window.HarunV5Systems=Object.freeze({version:'5.0.0',tarot,familiars,beings,daimons,pacts,state:()=>state(Core.getState().meta),drawTarot,chooseTarot,offerFamiliar:()=>offerCatalog('familiars',familiars,'FAMILIAR'),offerBeing:()=>offerCatalog('beings',beings,'SER'),offerDaimon:()=>offerCatalog('daimons',daimons,'DAIMON'),offerPact:()=>offerCatalog('pacts',pacts,'PACTO'),gain});
requestAnimationFrame(loop);
})();