(function(){
'use strict';
let seenWave=0,lastBoss=null,bossHandled=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),TAU=Math.PI*2;
function save(meta){try{localStorage.setItem('mundus_harun_survivor_v3',JSON.stringify(meta))}catch(_){}}
function makeEnemy(run,kind,x,y){const D=window.HarunSurvivorData,d=D.enemyKinds[kind],scale=1+run.wave*.047;return {kind,x,y,r:d.r,hp:d.hp*scale,maxHp:d.hp*scale,speed:d.speed*(1+run.wave*.005),damage:d.damage*(1+run.wave*.021),xp:d.xp,phase:rnd(0,TAU),hit:0,cd:rnd(.4,1.6),charge:0,poison:0,burn:0,v4:true}}
function appendDensity(run,target){const D=window.HarunSurvivorData,pool=['crawler','shade'];if(run.wave>=4)pool.push('charger');if(run.wave>=7)pool.push('seer');if(run.wave>=13)pool.push('tank');if(run.wave>=22)pool.push('warden');let need=Math.max(0,target-run.enemies.length);for(let i=0;i<need;i++){const side=i%4;let x,y;if(side===0){x=rnd(58,482);y=rnd(125,155)}else if(side===1){x=rnd(486,510);y=rnd(180,840)}else if(side===2){x=rnd(58,482);y=rnd(836,876)}else{x=rnd(30,54);y=rnd(180,840)};run.enemies.push(makeEnemy(run,pool[(i+run.wave)%pool.length],x,y))}}
function pact(run,v4,onDone){const el=document.querySelector('#v4Event'),banner=document.querySelector('#v4EventBanner'),title=document.querySelector('#v4EventTitle'),copy=document.querySelector('#v4EventCopy'),box=document.querySelector('#v4EventChoices');if(!el||!box){onDone();return}banner.textContent='PACTO DA CHAMA';title.textContent='Poder exige medida';copy.textContent='Sacrifique 15% do Sopro Vital Máximo por uma manifestação lendária, ou rejeite o pacto.';box.innerHTML='<button class="v4-choice" data-pact="reject" style="--c:#8be6c8"><b>REJEITAR</b><i>×</i><p>Preserve o Sopro Vital e prossiga sem o pacto.</p><small>SOBERANIA</small></button><button class="v4-choice legend" data-pact="accept" style="--c:#ffe36a"><b>VOZ DO DAIMON</b><i>◇</i><p>Sopro Vital Máx. ↓ · dano, crítico e velocidade de ataque ↑.</p><small>LENDÁRIO</small></button>';el.hidden=false;const finish=()=>{el.hidden=true;onDone()};box.querySelector('[data-pact="reject"]').onclick=finish;box.querySelector('[data-pact="accept"]').onclick=()=>{run.player.maxHp*=.85;run.player.hp=Math.min(run.player.hp,run.player.maxHp);v4.grant('daimon',1);finish()}}
function handleBossClear(st,run,v4){if(bossHandled||!lastBoss||lastBoss.hp>0)return;bossHandled=true;const w=run.wave,act=Math.min(5,Math.ceil(w/10));run.enemies=run.enemies.filter(e=>e!==lastBoss);run.enemyShots.length=0;run.boss=null;st.meta.essence=(st.meta.essence||0)+12;run.essenceRun=(run.essenceRun||0)+12;st.meta.bestWave=Math.max(st.meta.bestWave||0,w);if(act<5)st.meta.unlockedAct=Math.max(st.meta.unlockedAct||1,act+1);save(st.meta);if(w>=50){run.ended=true;st.meta.runs=(st.meta.runs||0)+1;st.meta.victories=(st.meta.victories||0)+1;st.meta.essence=(st.meta.essence||0)+40;save(st.meta);const toast=document.querySelector('#v4Toast');if(toast){toast.textContent='TRAVESSIA CONCLUÍDA · PEREGRINUS IGNIS';toast.hidden=false}setTimeout(()=>window.HarunSurvivorDebug.showMenu('campaign'),1100);return}run.wave=w+1;run.waveTime=0;seenWave=0;lastBoss=null;pact(run,v4,()=>{run.waveTime=0})}
function loop(){const core=window.HarunSurvivorDebug,v4=window.HarunSurvivorV4Debug;if(core&&v4){const st=core.getState(),r=st.run;if(st.state==='run'&&r){if(r.boss){lastBoss=r.boss;if(r.boss.hp>0)bossHandled=false}handleBossClear(st,r,v4);const eventVisible=!!document.querySelector('#v4Event:not([hidden])');if(eventVisible){r.enemies.length=0;r.enemyShots.length=0;r.waveTime=0}if(r.wave!==seenWave){seenWave=r.wave;if(r.wave%10!==0){const w=r.wave;setTimeout(()=>{const now=core.getState(),run=now.run,evt=document.querySelector('#v4Event:not([hidden])');if(now.state!=='run'||!run||run.wave!==w||evt)return;const floor=Math.min(18,6+Math.floor(w*.28));if(run.enemies.length<floor)appendDensity(run,floor)},220)}}}}requestAnimationFrame(loop)}
requestAnimationFrame(loop);
})();