(function(){
'use strict';
const Core=window.HarunSurvivorDebug,D=window.HarunSurvivorData;if(!Core||!D)throw new Error('V5 world requires Survivor core');
const $=s=>document.querySelector(s),frame=$('.frame'),TAU=Math.PI*2;
const roomTypes=[
 {id:'arena',name:'Câmara de Confronto',icon:'◇',special:false},{id:'relic',name:'Relicário',icon:'✦',special:true},{id:'shop',name:'Mercatorium',icon:'¤',special:true},{id:'scriptorium',name:'Scriptorium',icon:'≡',special:true},{id:'pact',name:'Sala do Pacto',icon:'⛓',special:true},{id:'sacrifice',name:'Ara do Sacrifício',icon:'△',special:true},{id:'throne',name:'Sala do Trono',icon:'♛',special:true},{id:'trial',name:'Sala de Provação',icon:'⚔',special:true},{id:'fortune',name:'Sala da Fortuna',icon:'☸',special:true},{id:'observatory',name:'Observatorium',icon:'◉',special:true},{id:'vault',name:'Cofre Sigilar',icon:'▣',special:true},{id:'veiled',name:'Câmara Velada',icon:'?',special:true},{id:'rest',name:'Câmara de Repouso',icon:'☾',special:true},{id:'rift',name:'Fenda Dimensional',icon:'✧',special:true}
];
const transitions=[
 {id:'descent',icon:'▽',text:'O chão se abre. Hārūn desce.'},{id:'portal',icon:'◌',text:'Um portal dobra a distância.'},{id:'ascent',icon:'△',text:'A passagem sobe para outra camada.'},{id:'sky',icon:'☼',text:'O teto se dissolve em céu.'},{id:'mirror',icon:'◇',text:'O espelho deixa de refletir e passa a atravessar.'},{id:'rift',icon:'✧',text:'A sala rasga uma fenda entre dimensões.'},{id:'throne',icon:'♛',text:'O trono abre a passagem seguinte.'},{id:'solar',icon:'☉',text:'Uma via solar conduz Hārūn adiante.'}
];
const ecosystems={
 o_olho:[['Sombra Sem Rosto','shade'],['Ruído Cego','crawler'],['Olho Velado','seer'],['Eco Mimético','seer'],['Larva do Automatismo','crawler']],
 a_chama:[['Cinza Rastejante','shade'],['Impulso Rubro','charger'],['Brasa Parasitária','crawler'],['Coro Reativo','seer'],['Devorador de Foco','warden']],
 a_fundacao:[['Pedra Inerte','tank'],['Peso de Chumbo','warden'],['Pilar Quebrado','seer'],['Carcereiro Sigilar','tank'],['Construtor Cego','warden']],
 heru_pa_khered:[['Sombra do Berço','crawler'],['Guardião Infantil','shade'],['Escaravelho Invertido','charger'],['Olho do Nascimento','seer'],['Máscara Pequena','crawler']],
 heru_sa_aset:[['Eco de Ísis','seer'],['Usurpador de Nome','shade'],['Carcereiro Lunar','warden'],['Serpente da Memória','charger'],['Censor de Filiação','tank']],
 heru_behdeti:[['Asa Cega','charger'],['Disco Partido','seer'],['Soldado de Behdet','shade'],['Guardião Solar','tank'],['Falcão Sombrio','warden']],
 a_eleicao:[['Escolhido Falso','shade'],['Voz da Massa','seer'],['Laço de Hábito','crawler'],['Censor de Escolha','tank'],['Arauto do Reflexo','warden']],
 a_balanca:[['Cobrador','charger'],['Peso Errante','tank'],['Medidor Cego','seer'],['Escriba da Dívida','warden'],['Moeda Morta','crawler']],
 a_vontade:[['Desejo Parasita','crawler'],['Falso Daimon','warden'],['Seta Desviada','charger'],['Voz Implantada','seer'],['Guardião do Desvio','tank']],
 o_carater:[['Máscara Fraturada','shade'],['Promessa Oca','crawler'],['Testemunha de Pedra','tank'],['Duplicador','seer'],['Censor da Palavra','warden']],
 a_disciplina:[['Devorador do Ritmo','charger'],['Atraso Vivo','crawler'],['Relógio Partido','seer'],['Peso da Repetição','tank'],['Interrupção','warden']],
 a_clareza:[['Névoa','shade'],['Ofuscador','seer'],['Ruído Branco','crawler'],['Espelho Turvo','warden'],['Censor da Causa','tank']],
 a_transmutacao:[['Escória Viva','crawler'],['Dragão de Escória','warden'],['Resíduo Rubro','charger'],['Forno Cego','tank'],['Alquimista Invertido','seer']],
 o_corpo:[['Exaustão','shade'],['Tirano da Exaustão','tank'],['Fome de Foco','crawler'],['Peso Muscular','charger'],['Censor Somático','warden']],
 a_obra:[['Arquiteto Cego','warden'],['Ferramenta Quebrada','crawler'],['Parede Móvel','tank'],['Projeto Morto','seer'],['Obra Inacabada','charger']],
 a_fortuna:[['Banqueiro Arcôntico','tank'],['Dívida Ambulante','crawler'],['Apostador Cego','charger'],['Cofre Vivo','warden'],['Contador do Acaso','seer']],
 a_influencia:[['Coro da Aprovação','seer'],['Eco Social','shade'],['Arauto Vazio','charger'],['Máscara Coletiva','warden'],['Censor da Voz','tank']],
 o_legado:[['Nome Apagado','shade'],['Guardião do Nome','tank'],['Escriba do Esquecimento','seer'],['Herdeiro Oco','crawler'],['Monumento Cego','warden']]
};
const generic=[['Espectro de Cinza','shade'],['Rastejante Arcôntico','crawler'],['Investidor do Limiar','charger'],['Vidente de Sal','seer'],['Censor','tank'],['Guardião Orbital','warden']];
let runRef=null,floor=null,currentRoom=-1,lastEnemySet=new WeakSet(),expanded=false,roomEventSeen=new Set(),magnetSeq=0,lastWave=0;
const shuffle=a=>a.slice().sort(()=>Math.random()-.5);
function systemsState(meta){meta.v5Systems=meta.v5Systems||{tarotSeen:[],tarotOwned:[],familiars:[],beings:[],daimons:[],pacts:[],relics:[],rituals:[],bestiary:[]};meta.v5Systems.bestiary=Array.isArray(meta.v5Systems.bestiary)?meta.v5Systems.bestiary:[];return meta.v5Systems}
function save(meta){try{localStorage.setItem(D.metaKey,JSON.stringify(meta))}catch(_){}}
function generateFloor(ctx){const middle=shuffle(roomTypes.filter(r=>!['arena','trial'].includes(r.id))).slice(0,8),seq=[roomTypes.find(r=>r.id==='arena'),...middle,roomTypes.find(r=>r.id==='trial')],usedLayouts=new Set();return seq.map((r,i)=>{let layout;do layout=`${r.id}-${1+Math.floor(Math.random()*64)}-${i}`;while(usedLayouts.has(layout));usedLayouts.add(layout);return{id:`room-${i}-${Date.now().toString(36)}`,index:i,type:r.id,name:r.name,icon:r.icon,special:r.special,layout,discovered:i===0,cleared:false,ctx:ctx?.node?.id||'unknown'}})}
function ensureUI(){if(!$('#v5MiniMap')){const m=document.createElement('aside');m.id='v5MiniMap';m.innerHTML='<header><b id="v5RoomName">CÂMARA</b><small>TAB · MAPA</small></header><div id="v5MiniNodes"></div>';frame.appendChild(m)}if(!$('#v5MapOverlay')){const s=document.createElement('section');s.id='v5MapOverlay';s.className='v5-overlay';s.hidden=true;s.innerHTML='<article class="v5-map-sheet"><small>MAPA DA TRAVESSIA</small><h2 id="v5MapTitle">CÂMARA</h2><p id="v5MapMeta"></p><div id="v5MapNodes"></div><footer>TAB · FECHAR MAPA</footer></article>';frame.appendChild(s)}if(!$('#v5Transition')){const t=document.createElement('div');t.id='v5Transition';t.hidden=true;frame.appendChild(t)}if(!$('#v5WorldFx')){const c=document.createElement('canvas');c.id='v5WorldFx';c.width=540;c.height=960;frame.appendChild(c)}}ensureUI();const fx=$('#v5WorldFx'),ctx=fx.getContext('2d');
function renderMap(){if(!floor)return;const r=Core.getState().run,ix=Math.max(0,currentRoom),room=floor[ix]||floor[0],html=floor.map((x,i)=>`<i class="${x.discovered?'seen':''} ${i===ix?'here':''} ${x.special?'special':''}" title="${x.name}"><b>${x.discovered?x.icon:'?'}</b></i>`).join('');$('#v5MiniNodes').innerHTML=html;$('#v5RoomName').textContent=room.name;$('#v5MapNodes').innerHTML=html;$('#v5MapTitle').textContent=room.name;$('#v5MapMeta').textContent=`${r?.v5Context?.node?.name||'TRAVESSIA'} · sala ${ix+1}/${floor.length} · ${room.layout}`}
function showTransition(room){const p=Core.getState().run?.v5Context||{},seed=room.index+(p.degree||0)+(p.phase==='ingressus'?2:p.phase==='student'?4:0),t=transitions[seed%transitions.length],el=$('#v5Transition');el.innerHTML=`<i>${t.icon}</i><b>${room.name}</b><span>${t.text}</span>`;el.hidden=false;window.MUNDUSAudio?.sfx('door');setTimeout(()=>el.hidden=true,900)}
function pause(on){const b=$('#pause'),st=Core.getState();if(st.state!=='run'||!b)return;if(on&&b.textContent!=='▶')b.click();if(!on&&b.textContent==='▶')b.click()}
function choiceHost(){let el=$('#v5Choice');if(!el){el=document.createElement('section');el.id='v5Choice';el.className='v5-overlay';frame.appendChild(el)}return el}
function simpleEvent(room,title,copy,actions){if(document.querySelector('#v5Choice:not([hidden])'))return;const el=choiceHost();pause(true);el.innerHTML=`<article class="v5-choice-shell"><small>${room.name}</small><h2>${title}</h2><p>${copy}</p><div class="v5-room-actions">${actions.map((a,i)=>`<button data-v5-room-action="${i}"><b>${a.name}</b><small>${a.desc}</small></button>`).join('')}</div></article>`;el.hidden=false;el.querySelectorAll('[data-v5-room-action]').forEach(b=>b.onclick=()=>{const a=actions[+b.dataset.v5RoomAction],next=a.run?.();el.hidden=true;el.innerHTML='';pause(false);if(typeof next==='function')setTimeout(next,70)})}
function enterSpecial(room){if(!room.special||roomEventSeen.has(room.id))return;roomEventSeen.add(room.id);const st=Core.getState(),r=st.run,S=window.HarunV5Systems;if(!r)return;setTimeout(()=>{if(room.type==='relic'||room.type==='scriptorium')S?.chooseTarot();else if(room.type==='pact')S?.offerPact();else if(room.type==='throne')S?.offerDaimon();else if(room.type==='trial')simpleEvent(room,'PROVA DA CÂMARA','Uma sequência mais densa protege a saída.',[{name:'ACEITAR A PROVA',desc:'Inimigos + dano; essência +10.',run(){r.enemies.forEach(e=>e.damage*=1.12);st.meta.essence=(st.meta.essence||0)+10;save(st.meta)}}]);else if(room.type==='observatory')simpleEvent(room,'OLHAR ALÉM','O Observatorium revela toda a travessia e amplia o crítico.',[{name:'ABRIR O OLHO',desc:'Revelar mapa · crítico ↑',run(){floor.forEach(x=>x.discovered=true);r.player.crit+=.05;renderMap()}}]);else if(room.type==='rest')simpleEvent(room,'REPOUSO','Uma pausa curta restaura parte do Sopro Vital.',[{name:'REPOUSAR',desc:'Recupera 35% do Sopro Vital.',run(){r.player.hp=Math.min(r.player.maxHp,r.player.hp+r.player.maxHp*.35)}}]);else if(room.type==='shop')simpleEvent(room,'MERCATORIUM','Troque moedas da run por poder.',[{name:'CARTA · 6 MOEDAS',desc:'Comprar uma escolha de Arcana.',run(){if(r.coins<6)return;r.coins-=6;return()=>S?.chooseTarot()}},{name:'SOPRO · 4 MOEDAS',desc:'Restaurar 30% de vida.',run(){if(r.coins>=4){r.coins-=4;r.player.hp=Math.min(r.player.maxHp,r.player.hp+r.player.maxHp*.3)}}}]);else if(room.type==='sacrifice')simpleEvent(room,'ARA DO SACRIFÍCIO','Entregue Sopro Vital para atravessar uma recompensa mais rara.',[{name:'SACRIFICAR 20%',desc:'Vida atual ↓ · recebe Arcana.',run(){r.player.hp=Math.max(1,r.player.hp-r.player.maxHp*.2);return()=>S?.chooseTarot()}},{name:'RECUSAR',desc:'Prosseguir sem custo.',run(){}}]);else if(room.type==='fortune')simpleEvent(room,'RODA DA FORTUNA','A roda pode multiplicar a essência ou convocar perigo.',[{name:'GIRAR',desc:'Essência +8 a +30; o risco pode subir.',run(){st.meta.essence=(st.meta.essence||0)+8+Math.floor(Math.random()*23);if(Math.random()<.35)r.enemies.forEach(e=>e.damage*=1.08);save(st.meta)}}]);else if(room.type==='vault')simpleEvent(room,'COFRE SIGILAR','O cofre contém uma manifestação guardada.',[{name:'ABRIR',desc:'Familiar ou Arcana aleatória.',run(){return Math.random()<.5?()=>S?.offerFamiliar():()=>S?.chooseTarot()}}]);else if(room.type==='veiled')simpleEvent(room,'CÂMARA VELADA','Algo não deveria estar neste mapa.',[{name:'ATRAVESSAR',desc:'Receber um Ser e aumentar risco.',run(){r.enemies.forEach(e=>e.damage*=1.1);return()=>S?.offerBeing()}}]);else if(room.type==='rift')simpleEvent(room,'FENDA DIMENSIONAL','A fenda troca segurança por um salto de poder.',[{name:'ENTRAR',desc:'Daimon ou Pacto.',run(){return Math.random()<.5?()=>S?.offerDaimon():()=>S?.offerPact()}}])},220)}
function spawnMagnet(r){if(!r||!r.gems||r.gems.some(g=>g.v5Magnet))return;const p=r.player;r.gems.push({x:Math.max(60,Math.min(480,p.x+(Math.random()-.5)*240)),y:Math.max(180,Math.min(840,p.y-180)),big:true,xp:0,v5Magnet:true,id:`magnet-${++magnetSeq}`})}
function magnetTick(r){const p=r.player,m=r.gems?.find(g=>g.v5Magnet);if(!m)return;if(Math.hypot(m.x-p.x,m.y-p.y)<42){r.gems=r.gems.filter(g=>g!==m);for(const g of r.gems){g.x=p.x;g.y=p.y}r.coins+=2;window.MUNDUSAudio?.sfx('pickup',{gain:1.25});const toast=$('#v4Toast');if(toast){toast.textContent='MAGNES ELECTORUM · TODOS OS DROPS ATRAÍDOS';toast.hidden=false;setTimeout(()=>toast.hidden=true,1500)}}}
function ecologyFor(r){return ecosystems[r.v5Context?.node?.id]||generic}
function idOf(r){return r.v5Context?.node?.id||''}
function applyEcology(r){const pool=ecologyFor(r),meta=Core.getState().meta,sys=systemsState(meta);let changed=false;for(const e of r.enemies){if(lastEnemySet.has(e)||e.kind==='boss')continue;lastEnemySet.add(e);const sp=pool[Math.floor(Math.random()*pool.length)];e.v5Species=sp[0];e.kind=sp[1];if(!sys.bestiary.includes(sp[0])){sys.bestiary.push(sp[0]);changed=true}if(idOf(r)==='o_olho'&&e.kind==='seer')e.damage*=.9;if(idOf(r)==='a_chama'&&e.kind==='charger')e.speed*=1.12;if(idOf(r)==='a_fundacao'&&e.kind==='tank'){e.hp*=1.18;e.maxHp*=1.18}}if(changed)save(meta)}
function drawWorld(r){ctx.clearRect(0,0,540,960);if(!r)return;const t=performance.now()/1000;for(const e of r.enemies){if(!e.v5Species||e.kind==='boss')continue;ctx.save();ctx.globalAlpha=.68;ctx.font='700 7px Manrope, sans-serif';ctx.textAlign='center';ctx.fillStyle='#dffbf3';ctx.shadowColor='#000';ctx.shadowBlur=4;ctx.fillText(e.v5Species,e.x,e.y-e.r-17);ctx.restore()}const m=r.gems?.find(g=>g.v5Magnet);if(m){ctx.save();ctx.translate(m.x,m.y);ctx.rotate(t*1.8);ctx.strokeStyle='#ffe36a';ctx.lineWidth=3;ctx.shadowColor='#ffe36a';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(0,0,14,0,TAU);ctx.stroke();ctx.fillStyle='#fff0a0';ctx.font='900 18px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('∩',0,0);ctx.restore()}}
window.addEventListener('keydown',e=>{if(e.code==='Tab'){e.preventDefault();e.stopImmediatePropagation();expanded=!expanded;$('#v5MapOverlay').hidden=!expanded;renderMap();window.MUNDUSAudio?.sfx(expanded?'book':'ui_back')}},true);
function loop(){const st=Core.getState(),r=st.run;if(st.state==='run'&&r){if(r!==runRef){runRef=r;floor=generateFloor(r.v5Context);currentRoom=0;lastWave=r.wave;lastEnemySet=new WeakSet();roomEventSeen=new Set();floor[0].discovered=true;r.player.speed*=1.28;r.player.fireRate=Math.max(.16,r.player.fireRate*.93);renderMap();showTransition(floor[0])}const ri=Math.min(floor.length-1,Math.floor(((r.wave-1)%50)/5));if(ri!==currentRoom){floor[currentRoom].cleared=true;currentRoom=ri;floor[currentRoom].discovered=true;renderMap();showTransition(floor[currentRoom]);if(r.wave%10!==0)enterSpecial(floor[currentRoom]);if(Math.random()<.2)spawnMagnet(r)}if(r.wave!==lastWave){lastWave=r.wave;if(r.wave%10===6&&Math.random()<.55)spawnMagnet(r)}applyEcology(r);magnetTick(r);drawWorld(r)}else{runRef=null;floor=null;currentRoom=-1;ctx.clearRect(0,0,540,960);$('#v5MiniMap').style.display='none'}if(st.state==='run')$('#v5MiniMap').style.display='';requestAnimationFrame(loop)}
window.HarunV5World=Object.freeze({version:'5.0.2',roomTypes,transitions,ecosystems,getFloor:()=>floor?JSON.parse(JSON.stringify(floor)):null,current:()=>floor&&currentRoom>=0?{...floor[currentRoom]}:null,spawnMagnet:()=>{const r=Core.getState().run;if(r)spawnMagnet(r)},forceRoomForQA(index){if(!floor)return false;currentRoom=Math.max(0,Math.min(floor.length-1,index));floor[currentRoom].discovered=true;renderMap();return true}});
requestAnimationFrame(loop);
})();