#!/usr/bin/env python3
from pathlib import Path
import json, re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "roguelite"
OUT.mkdir(parents=True, exist_ok=True)

def slug(s):
    s=s.lower()
    repl={"á":"a","à":"a","ã":"a","â":"a","é":"e","ê":"e","í":"i","ó":"o","ô":"o","õ":"o","ú":"u","ç":"c","æ":"ae"}
    for a,b in repl.items(): s=s.replace(a,b)
    return re.sub(r"[^a-z0-9]+","_",s).strip("_")

def common(id_, name, pool, effect, *, rarity="common", tags=None, eligibility=None, cost=None, duration=None, stacking=None, synergies=None, exclusions=None, provenance_level="dramatizacao_electorum", provenance_source="Design autoral Electorum", codex_category=None):
    return {"id":id_,"name":name,"rarity":rarity,"pool":pool,"eligibility":eligibility or {"min_stage":0,"min_cycle":0,"requires_tags":[],"forbids_tags":[]},"effect":effect,"cost":cost or {"resource":"none","amount":0},"duration":duration or {"mode":"instant","seconds":0,"rooms":0},"stacking":stacking or {"mode":"none","max_stacks":1},"synergies":synergies or [],"exclusions":exclusions or [],"vfx_hook":f"vfx.{id_}","sfx_hook":f"sfx.{id_}","save_state":{"scope":"run","persist":True},"codex":{"category":codex_category or pool,"summary":f"{name}: efeito de gameplay integrado ao sistema roguelite."},"provenance":{"level":provenance_level,"source":provenance_source},"tags":tags or []}

atu_names=[("the_fool","O Louco","threshold_reset"),("the_magus","O Mago","echo_instrument"),("the_priestess","A Sacerdotisa","secret_sight"),("the_empress","A Imperatriz","fecundity"),("the_emperor","O Imperador","command"),("the_hierophant","O Hierofante","tradition"),("the_lovers","Os Amantes","syzygy"),("the_chariot","O Carro","chariot"),("adjustment","Ajustamento","adjustment"),("the_hermit","O Eremita","hermit"),("fortune","Fortuna","fortune"),("lust","Luxúria","lust"),("the_hanged_man","O Enforcado","suspension"),("death","Morte","death"),("art","Arte","art"),("the_devil","O Diabo","devil"),("the_tower","A Torre","tower"),("the_star","A Estrela","star"),("the_moon","A Lua","moon"),("the_sun","O Sol","sun"),("the_aeon","O Aeon","aeon"),("the_universe","O Universo","universe")]
tarot=[]
for i,(sid,name,kind) in enumerate(atu_names):
    r=common(f"tarot_atu_{sid}",name,"tarot_atu",{"kind":kind,"power":1.0+i*0.03,"arcana_index":i,"runtime_event":f"arcana.{kind}"},rarity="rare" if i not in (0,10,20,21) else "legendary",tags=["tarot","atu",f"atu:{sid}"],synergies=["tag:arcana","tag:instrumentum"] if i%2==0 else ["tag:arcana","tag:power"],provenance_level="tradicao",provenance_source="Estrutura e nomenclatura do Tarot de Thoth; efeito de gameplay é dramatização Electorum",codex_category="Tarot de Thoth")
    r.update({"arcana_class":"atu","atu_index":i}); tarot.append(r)

suits={
"wands":("Bastões","fire",[("ace","Ás","ignite_seed",{"attack_bonus":0.18,"next_hit_ignite":True}),("2","Dois","split_will",{"choose":"speed_or_damage","rooms":1}),("3","Três","formation_chain",{"chain_count":3,"chain_scale":0.55}),("4","Quatro","war_stance",{"stationary_damage":0.24,"break_on_move":True}),("5","Cinco","overdrive_risk",{"damage":0.36,"self_heat":1}),("6","Seis","victory_resonance",{"on_kill_speed":0.20,"max_stacks":4}),("7","Sete","threshold_gambit",{"low_hp_damage":0.42,"hp_threshold":0.35}),("8","Oito","velocity_engine",{"projectile_speed":0.30,"move_speed":0.12}),("9","Nove","will_culmination",{"prevent_stagger":True,"charges":2}),("10","Dez","fire_overflow",{"convert_excess_focus_to_damage":True,"ratio":0.35})]),
"cups":("Copas","water",[("ace","Ás","focus_spring",{"focus_gain":30}),("2","Dois","bond_pair",{"link_echo":0.40,"rooms":1}),("3","Três","recovery_circle",{"heal_on_three_kills":3}),("4","Quatro","still_pool",{"focus_regen":0.8,"while_stationary":True}),("5","Cinco","wound_to_focus",{"damage_taken_focus":0.45}),("6","Seis","memory_recovery",{"restore_last_spent_resource":0.35}),("7","Sete","choice_of_cups",{"offer_three_boons":True,"one_is_ambivalent":True}),("8","Oito","flow_engine",{"dodge_focus":8,"perfect_dodge_bonus":10}),("9","Nove","overflow_heal",{"focus_cap_bonus":20,"overflow_to_heal":0.25}),("10","Dez","communion",{"room_clear_heal":4,"daimon_cooldown_pct":-0.15})]),
"swords":("Espadas","air",[("ace","Ás","reveal_edge",{"reveal_weakpoint":True,"precision":0.12}),("2","Dois","dual_mark",{"mark_two_targets":True,"mark_damage":0.16}),("3","Três","rupture_triangle",{"third_hit_armor_break":0.30}),("4","Quatro","quiet_blade",{"after_no_attack_sec":2.0,"next_crit":True}),("5","Cinco","precision_wager",{"crit_bonus":0.25,"miss_penalty_focus":5}),("6","Seis","line_of_truth",{"pierce":2,"reveal_path":True}),("7","Sete","feint",{"dodge_creates_decoy":True,"decoy_sec":1.5}),("8","Oito","analysis_engine",{"consecutive_hit_precision":0.04,"max_stacks":5}),("9","Nove","severance",{"execute_revealed_below":0.16}),("10","Dez","break_the_map",{"break_ward":True,"reveal_secret_candidate":True})]),
"disks":("Discos","earth",[("ace","Ás","material_seed",{"armor":8,"essence":4}),("2","Dois","balanced_exchange",{"reroll_cost_pct":-0.25,"economy_variance":0.10}),("3","Três","craft_triangle",{"upgrade_next_talisman":True}),("4","Quatro","anchor_stance",{"knockback_resist":1.0,"armor_while_still":6}),("5","Cinco","scarcity_alchemy",{"low_essence_defense":0.22,"threshold":10}),("6","Seis","equitable_return",{"shop_refund_chance":0.22}),("7","Sete","investment",{"bank_essence":5,"room_return":2}),("8","Oito","matter_engine",{"room_clear_armor_charge":3,"max_charges":4}),("9","Nove","fortress",{"barrier_charges":2,"barrier_value":12}),("10","Dez","matter_overflow",{"excess_armor_to_essence":0.20})])}
courts={"princess":("Princesa","manifest_field",{"manifestation":"suit_field","duration_sec":8}),"prince":("Príncipe","combo_engine",{"combo_window_sec":5,"combo_cap":6}),"queen":("Rainha","resource_aura",{"aura_radius":6,"conversion_rate":0.18}),"knight":("Cavaleiro","suit_finisher",{"finisher_power":1.6,"resets_suit_stacks":True})}
for suit,(pt,element,numbered) in suits.items():
    for rank,label,kind,payload in numbered:
        r=common(f"tarot_minor_{suit}_{rank}",f"{label} de {pt}",f"tarot_minor_{suit}",{"kind":kind,"suit":suit,"element":element,**payload},rarity="uncommon" if rank in {"4","5","6","7"} else "common",tags=["tarot","minor",f"suit:{suit}",f"element:{element}"],synergies=[f"tag:element:{element}",f"tag:suit:{suit}"],provenance_level="tradicao",provenance_source="Estrutura de naipe do Tarot de Thoth; mecânica é dramatização Electorum",codex_category="Tarot de Thoth"); r.update({"arcana_class":"minor","suit":suit,"rank":rank,"element":element}); tarot.append(r)
    for rank,(label,kind,payload) in courts.items():
        r=common(f"tarot_minor_{suit}_{rank}",f"{label} de {pt}",f"tarot_minor_{suit}",{"kind":kind,"suit":suit,"element":element,**payload},rarity="rare",tags=["tarot","minor","court",f"suit:{suit}",f"element:{element}"],synergies=[f"tag:suit:{suit}","tag:daimon","tag:instrumentum"],provenance_level="tradicao",provenance_source="Carta de corte do Tarot de Thoth; manifestação de gameplay é dramatização Electorum",codex_category="Tarot de Thoth"); r.update({"arcana_class":"minor","suit":suit,"rank":rank,"element":element}); tarot.append(r)

goetic_names="Bael,Agares,Vassago,Samigina,Marbas,Valefor,Amon,Barbatos,Paimon,Buer,Gusion,Sitri,Beleth,Leraje,Eligos,Zepar,Botis,Bathin,Sallos,Purson,Marax,Ipos,Aim,Naberius,Glasya-Labolas,Bune,Ronove,Berith,Astaroth,Forneus,Foras,Asmoday,Gaap,Furfur,Marchosias,Stolas,Phenex,Halphas,Malphas,Raum,Focalor,Vepar,Sabnock,Shax,Vine,Bifrons,Uvall,Haagenti,Crocell,Furcas,Balam,Alloces,Camio,Murmur,Orobas,Gremory,Ose,Amy,Orias,Vapula,Zagan,Valac,Andras,Haures,Andrealphus,Cimejes,Amdusias,Belial,Decarabia,Seere,Dantalion,Andromalius".split(",")
domains="command movement revelation rupture economy ward summon conversion precision tempo harvest risk".split(); triggers="room_enter primary_hit dodge enemy_kill room_clear player_damaged instrument_use arcana_use secret_discovered".split()
sigilla=[]
for n,name in enumerate(goetic_names,1):
    dom=domains[(n-1)%len(domains)]; trig=triggers[(n*5+3)%len(triggers)]; premium=(n%9)+1; price=(n%5)+1
    effect={"kind":"sigillum_contract","number":n,"spirit":name,"dominium":dom,"trigger":trig,"benefit":{"magnitude":round(0.08+premium*0.025,3),"variant":(n-1)//12,"signature":f"{dom}:{trig}:{n}"},"pretium":{"resource":["essence","focus","max_hp","curse_heat"][n%4],"amount":price,"risk_tier":1+(n%3)}}
    sigilla.append(common(f"sigillum_{n:02d}_{slug(name)}",f"Sigillum {name}","sigilla_goetica",effect,rarity=["common","uncommon","rare","rare","legendary"][n%5],tags=["sigillum",f"dominium:{dom}",f"trigger:{trig}"],cost=effect["pretium"],stacking={"mode":"refresh" if n%3 else "charges","max_stacks":1+(n%3)},synergies=[f"tag:dominium:{dom}","tag:sigillum"],provenance_level="tradicao",provenance_source="Nome tradicional da Ars Goetia; DOMINIUM, PRETIUM e mecânica são dramatização Electorum",codex_category="Sigilla Goetica"))

principles=["Sulphur","Mercurius","Sal"]; planets=["Sol","Lua","Mercúrio","Vênus","Marte","Júpiter","Saturno"]; benefits={"Sol":"damage","Lua":"focus","Mercúrio":"speed","Vênus":"recovery","Marte":"rupture","Júpiter":"essence","Saturno":"armor"}; pharmaka=[]
for pi,p in enumerate(principles):
    for pj,planet in enumerate(planets):
        effect={"kind":"pharmakon","principle":p.lower(),"planet":planet.lower(),"benefit":benefits[planet],"magnitude":round(0.12+pj*0.025+pi*0.02,3),"liability":["self_heat","random_swap","slow_recovery"][(pi+pj)%3],"unknown_until_use":True,"polarity":["volatile","ambivalent","stable"][pi]}
        pharmaka.append(common(f"pharmakon_{slug(p)}_{slug(planet)}",f"{p} de {planet}","pharmaka",effect,rarity="uncommon" if pi!=1 else "rare",tags=["pharmakon",f"planet:{slug(planet)}",f"principle:{slug(p)}"],stacking={"mode":"refresh","max_stacks":1},synergies=[f"tag:planet:{slug(planet)}"],provenance_level="interpretacao",provenance_source="Matriz hermético-alquímica 3×7 do cânone; efeito de gameplay é dramatização Electorum",codex_category="Pharmaka Hermetica"))

signs="Áries,Touro,Gêmeos,Câncer,Leão,Virgem,Libra,Escorpião,Sagitário,Capricórnio,Aquário,Peixes".split(","); stats="attack armor speed focus precision essence recovery rupture".split(); talismans=[]
for si,sign in enumerate(signs):
    for decan in (1,2,3):
        stat=stats[(si*3+decan-1)%len(stats)]; condition=["on_room_clear","while_full_focus","after_dodge"][decan-1]
        talismans.append(common(f"talisman_{slug(sign)}_{decan}",f"Talismã de {sign} · Decanato {decan}","talismans",{"kind":"decan_modifier","sign":sign.lower(),"decan":decan,"stat":stat,"condition":condition,"magnitude":round(0.04+0.01*decan+0.005*(si%4),3)},rarity="common" if decan==1 else "uncommon",tags=["talisman",f"sign:{slug(sign)}",f"decan:{decan}"],stacking={"mode":"additive","max_stacks":3},synergies=[f"tag:sign:{slug(sign)}"],provenance_level="interpretacao",provenance_source="Estrutura 12 signos × 3 decanatos do cânone; efeito é dramatização Electorum",codex_category="Talismãs Decânicos"))

instrumenta_defs=[("Bastão Ígneo","cone_fire","wands","fire"),("Vara Serpentina","chain_strike","wands","serpent"),("Cetro Solar","solar_burst","wands","solar"),("Bastão de Mercúrio","tempo_shift","wands","mercury"),("Vara de Marte","dash_break","wands","mars"),("Bastão da Chama Negra","black_flame","wands","black_flame"),("Cálice Lunar","focus_well","cups","moon"),("Taça do Véu","phase","cups","veil"),("Copa de Vênus","heal_link","cups","venus"),("Cratera de Sophia","transmute_hurt","cups","sophia"),("Cálice de Água Negra","curse_cleanse","cups","purge"),("Taça do Retorno","return","cups","return"),("Lâmina de Ruptura","armor_break","swords","rupture"),("Athame de Thoth","mark_reveal","swords","thoth"),("Espada Solar","line_beam","swords","solar"),("Faca do Verbum","silence","swords","verbum"),("Lâmina de Saturno","slow_cut","swords","saturn"),("Espada do Limiar","door_cut","swords","threshold"),("Disco de Saturno","fortify","disks","saturn"),("Pentáculo Solar","ward","disks","solar"),("Disco de Fortuna","reroll","disks","fortune"),("Selo de Terra","anchor","disks","earth"),("Moeda de Júpiter","multiply_essence","disks","jupiter"),("Placa de Belial","grounding","disks","belial"),("Espelho de Sophia","reflect","spiritus","sophia"),("Lâmpada de Phosphoros","reveal_all","spiritus","phosphoros"),("Livro do Verbum","command_wave","spiritus","verbum"),("Ampulheta de Kairos","time_stop","spiritus","kairos"),("Máscara de Paimon","dominate","spiritus","paimon"),("Olho de Hórus","precision","spiritus","horus"),("Tabuleta de Thoth","echo_card","spiritus","thoth"),("Chave Dracônica","red_path","spiritus","draconic")]; instrumenta=[]
for i,(name,kind,family,tag) in enumerate(instrumenta_defs): instrumenta.append(common(f"instrumentum_{slug(name)}",name,"instrumenta",{"kind":kind,"charge_cost":1+(i%3),"cooldown_rooms":1+(i%2),"magnitude":round(0.2+(i%7)*0.07,2)},rarity="rare" if family=="spiritus" else "uncommon",tags=["instrumentum",f"instrument_family:{family}",f"theme:{tag}"],duration={"mode":"timed" if kind in {"phase","time_stop","dominate","fortify","precision"} else "instant","seconds":3+(i%4),"rooms":0},stacking={"mode":"charges","max_stacks":3},synergies=[f"tag:theme:{tag}",f"tag:suit:{family}" if family in {"wands","cups","swords","disks"} else "tag:spiritus"],provenance_level="dramatizacao_electorum",provenance_source="Instrumentum canônico de CHRONICA HARUN; mecânica autoral Electorum",codex_category="Instrumenta"))

power_names=["Olho Revelatório","Chama Negra","Martelo de Fundação","Sigilo da Eleição","Balança Interna","Vetor da Vontade","Coluna de Caráter","Ritmo da Disciplina","Luz de Clareza","Serpente da Transmutação","Pulso Vital","Mão da Obra","Fortuna Sigilar","Verbum","Memoria Ignis"]; power_tags="reveal fire foundation election balance will character rhythm clarity transmutation vital work fortune verbum memory".split(); mutation_hooks=[["on_projectile_about_to_hit","modify_damage","on_enemy_killed"],["on_player_damaged","on_enemy_killed","modify_damage"],["modify_damage","on_room_cleared","passive_flags"],["on_room_cleared","on_dodge","passive_flags"],["on_player_damaged","on_room_cleared","passive_flags"],["modify_damage","on_dodge","on_enemy_killed"],["on_player_damaged","modify_damage","passive_flags"],["on_dodge","on_room_cleared","passive_flags"],["modify_damage","on_projectile_about_to_hit","passive_flags"],["on_enemy_killed","on_player_damaged","modify_damage"],["on_player_damaged","on_room_cleared","on_dodge"],["on_room_cleared","on_enemy_killed","passive_flags"],["on_room_cleared","on_enemy_killed","modify_damage"],["modify_damage","on_enemy_killed","passive_flags"],["on_room_cleared","on_dodge","passive_flags"]]; powers=[]; mutations=[]
for i,(name,tag) in enumerate(zip(power_names,power_tags),1):
    pid=f"power_{i:02d}_{slug(name)}"; powers.append(common(pid,name,"powers",{"kind":"matrix_power","matrix_index":i,"matrix_tag":tag,"cost_focus":10+(i%4)*5,"cooldown_sec":4+(i%5),"runtime_event":f"power.{tag}"},rarity="rare",tags=["power",f"matrix:{tag}"],synergies=[f"tag:matrix:{tag}",f"tag:theme:{tag}"],provenance_level="dramatizacao_electorum",provenance_source="Poder-Matriz canônico de CHRONICA HARUN",codex_category="Poderes-Matriz"))
    for variant in range(1,4):
        hook=mutation_hooks[i-1][variant-1]; mid=f"mutation_{i:02d}_{variant}_{tag}"
        mutations.append(common(mid,f"{name} · Mutação {variant}","mutations",{"kind":"mutation_hook","parent_power":pid,"hook":hook,"variant":variant,"operation":["amplify","convert","echo"][variant-1],"magnitude":round(0.10+0.06*variant+0.01*(i%5),2)},rarity="uncommon" if variant<3 else "rare",tags=["mutation",f"matrix:{tag}",f"hook:{hook}"],eligibility={"min_stage":0,"min_cycle":0,"requires_tags":[f"matrix:{tag}"],"forbids_tags":[]},synergies=[pid,f"tag:matrix:{tag}"],provenance_level="dramatizacao_electorum",provenance_source="Mutação funcional autoral vinculada ao Poder-Matriz canônico",codex_category="Mutações"))

daimon_defs=[("Daimon Lampadário","reveal_secret","reveal"),("Daimon Serpentino","execute_bite","serpent"),("Daimon Escriba","echo_arcana","arcana"),("Daimon Specular","echo_attack","reflect"),("Daimon Funerário","corpse_essence","death"),("Daimon Saturnino","intercept_projectile","saturn"),("Daimon Solar","purge_curse","solar")]; daimones=[]
for i,(name,action,tag) in enumerate(daimon_defs): daimones.append(common(f"daimon_{slug(name.replace('Daimon ','').strip())}",name,"daimones",{"kind":"daimon_action","action":action,"cooldown_sec":6+i,"range":4+i%3,"magnitude":round(0.25+0.08*i,2)},rarity="rare",tags=["daimon",f"theme:{tag}"],synergies=[f"tag:theme:{tag}","tag:court"],provenance_level="dramatizacao_electorum",provenance_source="Daimon canônico de CHRONICA HARUN; função mecânica autoral",codex_category="Daimones"))

relic_names=["Espelho de Sophia","Fragmento do Pleroma","Olho do Cego","Coroa Quebrada","Cinza de Phosphoros","Disco de Saturno","Selo de Belial","Véu de Lilith","Pena de Thoth"]; relic_kinds="reflect_rule pleroma_balance blindspot_trade broken_crown phosphoros_ember saturn_cycle belial_ground lilith_veil thoth_inscription".split(); relics=[]
for i,(name,kind) in enumerate(zip(relic_names,relic_kinds)): relics.append(common(f"relic_{slug(name)}",name,"relics",{"kind":kind,"rule_change":True,"magnitude":round(0.15+0.05*i,2)},rarity="legendary",tags=["relic",f"relic_rule:{kind}"],stacking={"mode":"none","max_stacks":1},synergies=["tag:relic"],provenance_level="dramatizacao_electorum",provenance_source="Relíquia canônica inicial de CHRONICA HARUN",codex_category="Relíquias"))

trans_defs=[("Forma do Olho Desvelado",["reveal","precision","thoth"],"reveal_mastery"),("Corpus Ignis",["fire","will","black_flame"],"fire_mastery"),("Armadura de Horos",["foundation","earth","saturn"],"boundary_mastery"),("Syzygia Lunar",["water","bond","moon"],"bond_mastery"),("Verbum Incisivo",["verbum","air","rupture"],"word_mastery"),("Pele Dracônica",["draconic","serpent","transmutation"],"draconic_mastery"),("Espelho Vivo",["reflect","sophia","clarity"],"reflection_mastery"),("Coroa sem Trono",["command","election","belial"],"sovereignty_mastery"),("Motor de Fortuna",["fortune","jupiter","economy"],"fortune_mastery"),("Memória Ígnea",["memory","fire","arcana"],"memory_mastery"),("Coluna Solar",["solar","character","vital"],"solar_mastery"),("Mão do Artífice",["work","matter","foundation"],"craft_mastery")]; transformations=[]
for name,req,result in trans_defs: transformations.append(common(f"transformation_{slug(name)}",name,"transformations",{"kind":"transformation","required_tags":[f"theme:{t}" for t in req],"threshold":3,"result":result,"visual_hook":f"transform.{result}"},rarity="legendary",tags=["transformation",f"transform:{result}"],stacking={"mode":"unique_transform","max_stacks":1},synergies=[f"tag:theme:{req[0]}"],provenance_level="dramatizacao_electorum",provenance_source="Transformação autoral Electorum para buildcraft",codex_category="Transformações"))

curse_defs=[("Regime da Urgência","urgency",{"room_timer_pct":-0.18,"reward_rarity":0.08}),("Regime da Visibilidade","visibility",{"hidden_feedback":True,"elite_reward":0.12}),("Regime da Escassez","scarcity",{"pickup_rate":-0.20,"shop_power":0.15}),("Regime da Pureza","purity",{"mixed_tags_penalty":0.12,"mono_tag_bonus":0.10}),("Regime da Hierarquia Total","hierarchy",{"elite_aura":0.15,"boss_reward":0.12}),("Regime da Identidade","identity",{"pool_lock":1,"locked_pool_bonus":0.16}),("Regime da Repetição","repetition",{"repeat_enemy_strength":0.10,"repeat_reward":0.08}),("Cegueira de Segunda Ordem","second_order_blindness",{"map_uncertainty":True,"secret_weight":0.20})]; curses=[]
for i,(name,key,mods) in enumerate(curse_defs): curses.append(common(f"curse_{key}",name,"curses",{"kind":"curse","modifiers":mods,"risk_tier":1+(i%3)},rarity="rare",tags=["curse",f"curse:{key}"],stacking={"mode":"none","max_stacks":1},synergies=["tag:curse"],provenance_level="dramatizacao_electorum",provenance_source="Dramatização Electorum inspirada nos regimes arcônticos do Liber Yaldabaoth; não apresentada como doutrina antiga",codex_category="Maldições"))
bless_defs=[("Lucidez de Horos","horos",{"precision":0.12,"map_clarity":True}),("Fogo de Phosphoros","phosphoros",{"damage":0.10,"curse_resist":0.12}),("Memória de Thoth","thoth",{"arcana_echo_chance":0.16}),("Olho de Hórus","horus",{"weakpoint_bonus":0.18}),("Fundamento de Belial","belial",{"armor":8,"knockback_resist":0.5}),("Sophia Reintegrada","sophia",{"focus_regen":0.18,"transmute_loss":0.15})]; blessings=[]
for name,key,mods in bless_defs: blessings.append(common(f"blessing_{key}",name,"blessings",{"kind":"blessing","modifiers":mods},rarity="rare",tags=["blessing",f"blessing:{key}"],stacking={"mode":"none","max_stacks":1},synergies=[f"tag:theme:{key}"],provenance_level="dramatizacao_electorum",provenance_source="Bênção autoral Electorum para CHRONICA HARUN",codex_category="Bênçãos"))
route_defs=[("Rota do Olho","eye",["reveal","precision"],"information"),("Rota da Chama","flame",["fire","will"],"aggression"),("Rota da Obra","work",["work","foundation"],"construction"),("Rota do Daimon","daimon",["daimon","memory"],"companionship"),("Rota do Pleroma","pleroma",["balance","sophia"],"integration"),("Rota Arcôntica","archontic",["command","risk"],"dominion"),("Rota Dracônica","draconic",["draconic","transmutation"],"transformation"),("Rota do Limiar","threshold",["threshold","secret"],"hidden_path")]; routes=[]
for i,(name,key,tags_,bias) in enumerate(route_defs): routes.append(common(f"route_{key}",name,"routes",{"kind":"route","route_index":i,"affinity_tags":[f"theme:{t}" for t in tags_],"reward_bias":bias,"route_modifier":round(0.05+0.015*i,3)},rarity="rare",tags=["route",f"route:{key}"],stacking={"mode":"none","max_stacks":1},exclusions=[f"route_{k}" for _,k,_,_ in route_defs if k!=key],synergies=[f"tag:theme:{tags_[0]}"],provenance_level="dramatizacao_electorum",provenance_source="Nome e mecânica de rota autorais Electorum; as fontes canônicas fixam a contagem de oito rotas, não estes nomes",codex_category="Rotas"))

room_specs=[("Câmara do Arcano","arcana","special",1.0,"tarot",{"resource":"none","amount":0},"choice_lock"),("Reliquarium","reliquary","special",0.50,"relics",{"resource":"essence","amount":10},"rarity_debt"),("Instrumentarium","instrumentarium","special",0.80,"instrumenta",{"resource":"essence","amount":6},"charge_tax"),("Laboratorium","laboratorium","special",0.70,"pharmaka",{"resource":"none","amount":0},"unknown_pharmakon"),("Câmara Sigillar","sigillar","special",0.65,"sigilla_goetica",{"resource":"essence","amount":4},"pretium"),("Mercado de Essência","essence_market","special",0.90,"market",{"resource":"none","amount":0},"market_variance"),("Bibliotheca","bibliotheca","special",0.55,"codex",{"resource":"none","amount":0},"opportunity_cost"),("Speculum","speculum","special",0.45,"reroll",{"resource":"focus","amount":10},"reflection"),("Câmara Planetária","planetary","special",0.50,"planetary",{"resource":"none","amount":0},"planetary_bias"),("Câmara de Provação","trial","trial",0.65,"trial_reward",{"resource":"none","amount":0},"combat_trial"),("Câmara Maldita","cursed","cursed",0.45,"curses",{"resource":"hp","amount":8},"curse"),("Sala Secreta","secret","secret",1.00,"secret_reward",{"resource":"rupture","amount":1},"resource_spend"),("Sala Duplamente Secreta","super_secret","super_secret",0.35,"super_secret_reward",{"resource":"rupture","amount":1},"high_variance"),("Câmara do Arconte","archon","special",0.25,"archon_event",{"resource":"essence","amount":8},"archontic_debt"),("Câmara Teofânica","theophany","special",0.18,"theophany",{"resource":"none","amount":0},"judgement"),("Câmara Histórica","historical_echo","special",0.30,"historical_echo",{"resource":"none","amount":0},"interpretive_choice"),("Câmara de Iniciação","initiation","initiation",1.0,"initiation",{"resource":"none","amount":0},"threshold"),("Câmara Pneumática","pneumatic","postboss",0.45,"blessings",{"resource":"none","amount":0},"route_commitment"),("Câmara Ctônica","chthonic","postboss",0.45,"pact_reward",{"resource":"max_hp","amount":8},"curse_heat"),("Mesa do Pacto","pact_table","postboss",0.35,"sigilla_goetica",{"resource":"essence","amount":12},"contract_debt")]; rooms=[]
for i,(name,key,role,weight,reward_pool,cost,risk) in enumerate(room_specs):
    secret=role in {"secret","super_secret"}; post=role=="postboss"; entry={"mode":"hidden_wall" if secret else ("postboss_portal" if post else "door"),"accepted_openers":["ritual_bomb","rupture_charge","wall_break"] if secret else [],"requires_discovery":secret}; elig={"min_stage":0,"min_cycle":0,"requires_tags":[],"forbids_tags":[]}
    if key=="initiation": elig["requires_tags"]=["journey:ready_for_initiation"]
    if key=="pneumatic": elig["requires_tags"]=["postboss:cleared"]; elig["forbids_tags"]=["debt:severe"]
    if key=="chthonic": elig["requires_tags"]=["postboss:cleared"]; elig["forbids_tags"]=["blessing:sealed"]
    if key=="pact_table": elig["requires_tags"]=["postboss:cleared"]; elig["forbids_tags"]=["pact:locked"]
    r=common(f"room_{key}",name,"special_rooms",{"kind":"room_event","event":key,"reward_pool":reward_pool,"weight":weight,"risk":risk},rarity="rare" if role not in {"secret","super_secret"} else "legendary",tags=["room",f"room_role:{role}"],eligibility=elig,cost=cost,stacking={"mode":"none","max_stacks":1},synergies=[f"tag:room_role:{role}"],provenance_level="dramatizacao_electorum",provenance_source="Sala canônica de CHRONICA HARUN" if i<17 else "Escolha pós-chefe autoral Electorum inspirada apenas em princípios genéricos de risco/recompensa",codex_category="Salas Especiais")
    r.update({"room_role":role,"spawn_condition":{"weight":weight,"once_per_floor":True},"entry":entry,"risk":{"kind":risk},"reward":{"pool":reward_pool,"choices":1+(i%2)},"runtime_event":f"room.{key}","persistent_state":{"visited":True,"resolved":True},"map_icon":f"map.room.{key}","discovery_feedback":f"discover.room.{key}","postboss":post,"exclusive_group":"postboss_path" if post else None}); rooms.append(r)

catalogs={"tarot":tarot,"sigilla":sigilla,"pharmaka":pharmaka,"talismans":talismans,"instrumenta":instrumenta,"powers":powers,"mutations":mutations,"daimones":daimones,"relics":relics,"transformations":transformations,"curses":curses,"blessings":blessings,"routes":routes,"special_rooms":rooms}
for name,records in catalogs.items(): (OUT/f"{name}.json").write_text(json.dumps(records,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
print({k:len(v) for k,v in catalogs.items()})
