from pathlib import Path
src=Path('dist/index.html')
s=src.read_text()

# CSS
css='''
.entry-paths{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:26px auto 10px;max-width:860px}.entry-path{padding:20px;border:1px solid rgba(232,181,92,.28);border-radius:18px;background:rgba(6,22,31,.56);text-align:left;cursor:pointer;color:var(--text);transition:.22s ease}.entry-path:hover{transform:translateY(-2px);border-color:rgba(232,181,92,.65);box-shadow:0 14px 40px rgba(0,0,0,.24)}.entry-path b{display:block;color:var(--gold);font-size:15px;letter-spacing:.03em}.entry-path small{display:block;margin-top:7px;color:var(--muted);line-height:1.45}.entry-custom{max-width:860px;margin:18px auto 0;text-align:left;border:1px solid rgba(65,207,206,.26);border-radius:20px;padding:20px;background:linear-gradient(145deg,rgba(7,29,40,.82),rgba(17,12,28,.72))}.entry-custom label{display:block;font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:var(--teal);margin-bottom:10px}.entry-custom textarea{width:100%;min-height:122px;resize:vertical;border:1px solid rgba(255,255,255,.13);border-radius:14px;padding:15px 16px;background:rgba(0,0,0,.24);color:var(--text);font:inherit;line-height:1.55;box-sizing:border-box}.entry-custom textarea:focus{outline:none;border-color:rgba(232,181,92,.68);box-shadow:0 0 0 3px rgba(232,181,92,.08)}.entry-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.entry-actions .btn{width:auto;flex:1 1 230px}.entry-error{min-height:18px;color:#f0a0a0;font-size:13px;margin-top:8px}.question-refine{margin-top:18px;border:1px solid rgba(232,181,92,.35);border-radius:18px;padding:18px;background:rgba(11,20,30,.72)}.question-refine .row{padding:9px 0;border-bottom:1px solid rgba(255,255,255,.07)}.question-refine .row:last-child{border-bottom:0}.question-refine span{display:block;color:var(--muted);font-size:11px;letter-spacing:.12em;text-transform:uppercase;margin-bottom:4px}.question-refine b{display:block;color:var(--text);line-height:1.5}.question-refine .suggested{color:var(--gold);font-family:var(--serif);font-size:21px;line-height:1.35}.micro-win{margin-top:14px;padding:11px 13px;border-left:2px solid var(--teal);background:rgba(65,207,206,.06);color:var(--muted);font-size:13px}.v10-question-anchor{margin:18px 0 22px;padding:16px 18px;border:1px solid rgba(65,207,206,.28);border-radius:16px;background:rgba(65,207,206,.05)}.v10-question-anchor span,.v10-question-anchor small{display:block;color:var(--muted);font-size:11px;letter-spacing:.1em;text-transform:uppercase}.v10-question-anchor b{display:block;margin:7px 0;color:var(--text);font-family:var(--serif);font-size:20px;line-height:1.38}@media(max-width:720px){.entry-paths{grid-template-columns:1fr}.entry-actions{display:grid}.entry-actions .btn{width:100%}.question-refine .suggested{font-size:18px}}
'''
s=s.replace('</style>', css+'</style>',1)

# state
s=s.replace("const STATE_KEY='H93_OF_001_V10_STATE';", "const STATE_KEY='H93_OF_001_V10_2_STATE';")
s=s.replace("const OLD_STATE_KEYS=[", "const OLD_STATE_KEYS=['H93_OF_001_V10_STATE',",1)
s=s.replace("const initial=()=>({version:'10',step:0,answers:{},micro:{},spread:[],card:null,cardPos:null,lead:{},product:null,bumps:[],payment:null,upsells:[],downsell:false,postStage:'magnet',utm:{}});", "const initial=()=>({version:'10.2',step:0,answers:{},micro:{},spread:[],card:null,cardPos:null,lead:{},questionMode:'',questionRaw:'',questionSuggested:'',entryQuestion:'',questionAxis:'',product:null,bumps:[],payment:null,upsells:[],downsell:false,postStage:'magnet',utm:{}});")
s=s.replace("version:'10',micro:x?.micro||{}", "version:'10.2',micro:x?.micro||{}")

# prevent bypassing the opening question
s=s.replace("function next(){const m=MICRO_PROMPTS[state.step];","function next(){if(state.step===0&&!state.entryQuestion)return;const m=MICRO_PROMPTS[state.step];",1)

# functions
anchor="function answer(key,id){state.answers[key]=id;save();next()}"
new_funcs=r'''const DEFAULT_ENTRY_QUESTION='O que está impedindo o dinheiro de entrar ou permanecer na sua vida?';
function activeQuestion(){return (state.entryQuestion||state.questionSuggested||state.questionRaw||DEFAULT_ENTRY_QUESTION).trim()}
function entryAxisFrom(text){const t=String(text||'').toLowerCase();const entry=/(entrar|entra|ganhar|ganho|renda|fatur|venda|cliente|receita)/.test(t),stay=/(permane|manter|guardar|some|sumir|gasto|d[ií]vida|conta|sobra|acumular)/.test(t);if(entry&&stay)return'entrada e permanência';if(/(crescer|crescimento|invest|patrim|expand|escala|multiplicar)/.test(t))return'crescimento';if(/(medo|travo|trava|decid|decisão|ansied|controle|risco)/.test(t))return'decisão sob pressão';if(stay)return'permanência';if(entry)return'entrada';return'entrada e permanência'}
function refinedEntryQuestion(text){const axis=entryAxisFrom(text);const map={entrada:'O que está bloqueando a entrada de dinheiro e quais padrões precisam mudar para eu criar uma geração financeira mais consistente?',permanência:'O que em meus padrões e decisões faz o dinheiro entrar, mas impede que ele permaneça e se transforme em estabilidade?',crescimento:'O que está impedindo o dinheiro que já entra de crescer, ganhar estrutura e se converter em patrimônio?','decisão sob pressão':'Que padrão assume o controle das minhas decisões financeiras quando sinto pressão, medo ou risco, e como isso interfere no dinheiro que entra ou permanece?','entrada e permanência':DEFAULT_ENTRY_QUESTION};return map[axis]||DEFAULT_ENTRY_QUESTION}
function startGuidedQuestion(){state.questionMode='guided';state.questionRaw='';state.questionSuggested='';state.questionAxis='entrada e permanência';state.entryQuestion=DEFAULT_ENTRY_QUESTION;state.step=1;save();render();window.scrollTo({top:0,behavior:'smooth'})}
function startCustomQuestion(){state.questionMode='custom';save();render();setTimeout(()=>document.getElementById('entryQuestion')?.focus(),30)}
function editEntryQuestion(){state.questionMode='custom';state.questionSuggested='';save();render();setTimeout(()=>document.getElementById('entryQuestion')?.focus(),30)}
function refineEntryQuestion(){const el=document.getElementById('entryQuestion'),err=document.getElementById('entryError');const raw=String(el?.value||state.questionRaw||'').trim();if(raw.length<8){if(err)err.textContent='Escreva um pouco mais sobre a situação para eu organizar a pergunta.';return}state.questionRaw=raw;state.questionAxis=entryAxisFrom(raw);state.questionSuggested=refinedEntryQuestion(raw);state.entryQuestion='';save();render()}
function acceptEntryQuestion(useSuggested){state.entryQuestion=(useSuggested?state.questionSuggested:state.questionRaw)||DEFAULT_ENTRY_QUESTION;state.questionAxis=state.questionAxis||entryAxisFrom(state.entryQuestion);state.questionMode='accepted';state.step=1;save();render();window.scrollTo({top:0,behavior:'smooth'})}
'''
if anchor not in s: raise SystemExit('answer anchor missing')
s=s.replace(anchor,new_funcs+anchor,1)

# case0
start=s.index('case 0:h=`')
end=s.index('`;break;',start)+len('`;break;')
case0=r'''case 0:{const custom=state.questionMode==='custom'||Boolean(state.questionSuggested);const suggested=Boolean(state.questionSuggested);h=`<div class="content center"><div class="eyebrow">Experiência oracular · Frater Hórus L93</div><h1>O que está impedindo o dinheiro de <span class="accent">entrar ou permanecer na sua vida?</span></h1><p class="lead center">Você pode deixar o Oráculo localizar o ponto central do bloqueio ou começar por uma situação financeira específica que já está ocupando sua mente.</p><div class="preview-cards"><div class="mini-card"></div><div class="mini-card"></div><div class="mini-card"></div></div><div class="entry-paths"><button class="entry-path" onclick="startGuidedQuestion()"><b>QUERO DESCOBRIR O QUE ESTÁ BLOQUEANDO</b><small>O percurso cruza suas respostas e a tiragem para localizar o eixo principal sem exigir que você saiba formular o problema agora.</small></button><button class="entry-path" onclick="startCustomQuestion()"><b>JÁ TENHO UMA QUESTÃO ESPECÍFICA</b><small>Escreva a situação com suas palavras. Antes da carta, o sistema organiza uma pergunta mais precisa para você aprovar ou manter como escreveu.</small></button></div>${custom?`<div class="entry-custom"><label>Sua situação financeira</label>${suggested?`<div class="question-refine"><div class="row"><span>O que você trouxe</span><b>${esc(state.questionRaw)}</b></div><div class="row"><span>Eixo identificado</span><b>${esc(state.questionAxis)}</b></div><div class="row"><span>Pergunta sugerida para a tiragem</span><b class="suggested">${esc(state.questionSuggested)}</b></div></div><div class="micro-win"><b>Primeiro ganho:</b> sua questão já saiu de uma preocupação ampla e ganhou um eixo investigável antes mesmo da carta.</div><div class="entry-actions"><button class="btn btn-primary" onclick="acceptEntryQuestion(true)">USAR ESTA PERGUNTA</button><button class="btn btn-secondary" onclick="acceptEntryQuestion(false)">MANTER A MINHA</button><button class="btn btn-ghost" onclick="editEntryQuestion()">EDITAR</button></div>`:`<textarea id="entryQuestion" maxlength="500" placeholder="Ex.: Eu consigo fazer dinheiro entrar, mas sempre acontece alguma coisa e ele desaparece antes de eu construir estabilidade.">${esc(state.questionRaw)}</textarea><div id="entryError" class="entry-error"></div><div class="entry-actions"><button class="btn btn-primary" onclick="refineEntryQuestion()">ORGANIZAR MINHA PERGUNTA</button><button class="btn btn-ghost" onclick="startGuidedQuestion()">PREFIRO O DIAGNÓSTICO GUIADO</button></div>`}</div>`:''}<div class="price-note">Tiragem inicial gratuita · o primeiro resultado e o diagnóstico aparecem antes de qualquer oferta</div><p class="micro">Sua pergunta aprovada acompanha a tiragem, o diagnóstico e o PDF final.</p></div>`;break}'''
s=s[:start]+case0+s[end:]

# case2 context
old="case 2:h=`<div class=\"content\">${qScreen('pain','Comece pela situação real')}</div>`;break;"
new="case 2:h=`<div class=\"content\">${qScreen('pain','Comece pela situação real',`Pergunta que orienta esta tiragem: <b>${esc(activeQuestion())}</b>`)}</div>`;break;"
if old not in s: raise SystemExit('case2 missing')
s=s.replace(old,new,1)

# case19 prefill and wording
old19='''case 19:h=`<div class="content"><div class="eyebrow">Dados da consulta</div><h2>Agora organize sua questão principal.</h2><p class="lead">Nome, nascimento e contexto ajudam a conectar sua pergunta ao percurso já construído.</p><div class="form-grid"><div class="field"><label>Nome completo</label><input id="name" value="${esc(state.lead.name||'')}"></div><div class="field"><label>E-mail</label><input id="email" type="email" autocomplete="email" placeholder="voce@exemplo.com" value="${esc(state.lead.email||'')}"></div><div class="field"><label>Data de nascimento</label><input id="birth" type="date" value="${esc(state.lead.birth||'')}"></div><div class="field"><label>Hora de nascimento, se souber</label><input id="time" type="time" value="${esc(state.lead.time||'')}"></div><div class="field full"><label>Qual é a questão financeira que mais exige clareza?</label><textarea id="question" placeholder="Descreva a situação, a decisão ou o ciclo que deseja compreender.">${esc(state.lead.question||'')}</textarea></div></div><button class="btn btn-primary" onclick="saveLead()">PROCESSAR MEU DIAGNÓSTICO</button><p class="v9-local-note">Seu diagnóstico é montado nesta sessão. O envio transacional por e-mail só é liberado quando o canal de saída estiver operacional.</p></div>`;break;'''
new19='''case 19:h=`<div class="content"><div class="eyebrow">Dados da consulta</div><h2>Agora conecte a pergunta à sua leitura.</h2><p class="lead">Sua pergunta de abertura já está aqui. Você pode acrescentar um detalhe antes do processamento final.</p><div class="v10-question-anchor"><span>Pergunta escolhida</span><b>${esc(activeQuestion())}</b><small>Eixo: ${esc(state.questionAxis||'entrada e permanência')}</small></div><div class="form-grid"><div class="field"><label>Nome completo</label><input id="name" value="${esc(state.lead.name||'')}"></div><div class="field"><label>E-mail</label><input id="email" type="email" autocomplete="email" placeholder="voce@exemplo.com" value="${esc(state.lead.email||'')}"></div><div class="field"><label>Data de nascimento</label><input id="birth" type="date" value="${esc(state.lead.birth||'')}"></div><div class="field"><label>Hora de nascimento, se souber</label><input id="time" type="time" value="${esc(state.lead.time||'')}"></div><div class="field full"><label>Sua pergunta para a tiragem</label><textarea id="question" placeholder="Acrescente algum contexto se desejar.">${esc(state.lead.question||activeQuestion())}</textarea></div></div><button class="btn btn-primary" onclick="saveLead()">PROCESSAR MEU DIAGNÓSTICO</button><p class="v9-local-note">A pergunta escolhida acompanha o diagnóstico e o PDF final.</p></div>`;break;'''
if old19 not in s: raise SystemExit('case19 missing')
s=s.replace(old19,new19,1)

# case21 anchor
old21='''case 21:{const m=v10Model();h=`<div class="content"><div class="eyebrow">Sua Cartografia Financeira Inicial</div><div class="v10-kicker">O padrão que ganhou mais peso no seu percurso</div><h2>${esc(m.headline)}</h2><div class="v10-personal-lead">${esc(m.lead)}</div><div class="v9-diag">'''
new21='''case 21:{const m=v10Model();h=`<div class="content"><div class="eyebrow">Sua Cartografia Financeira Inicial</div><div class="v10-kicker">O padrão que ganhou mais peso no seu percurso</div><h2>${esc(m.headline)}</h2><div class="v10-personal-lead">${esc(m.lead)}</div><div class="v10-question-anchor"><span>Pergunta que organizou esta leitura</span><b>${esc(state.lead.question||activeQuestion())}</b><small>Eixo identificado: ${esc(state.questionAxis||'entrada e permanência')}</small></div><div class="v9-diag">'''
if old21 not in s: raise SystemExit('case21 missing')
s=s.replace(old21,new21,1)

# PDF include question
oldpdf="<h1>Diagnóstico Financeiro de THOTH</h1><p><b>'+clean(state.lead.name||'Consulente')+'</b></p><h2>Padrão dominante</h2>"
newpdf="<h1>Diagnóstico Financeiro de THOTH</h1><p><b>'+clean(state.lead.name||'Consulente')+'</b></p><h2>Pergunta da tiragem</h2><p>'+clean(state.lead.question||activeQuestion())+'</p><h2>Padrão dominante</h2>"
if oldpdf not in s: raise SystemExit('pdf missing')
s=s.replace(oldpdf,newpdf,1)

# exports
oldexp='window.next=next;window.chooseMicro=chooseMicro;'
newexp='window.next=next;window.startGuidedQuestion=startGuidedQuestion;window.startCustomQuestion=startCustomQuestion;window.editEntryQuestion=editEntryQuestion;window.refineEntryQuestion=refineEntryQuestion;window.acceptEntryQuestion=acceptEntryQuestion;window.chooseMicro=chooseMicro;'
if oldexp not in s: raise SystemExit('exports missing')
s=s.replace(oldexp,newexp,1)

src.write_text(s)
Path('dist/H93-OF-001-Oraculo-Financeiro-THOTH-V10.html').write_text(s)
print(f'V10.2 aplicada: {len(s)} caracteres')
