import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync('dist/index.html','utf8');
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(x=>x[1]);
const runtime=scripts.find(x=>x.includes("H93_OF_001_V11_1_STATE"));
if(!runtime)throw new Error('Runtime V11.1 ausente');
const mkNode=()=>({value:'',innerHTML:'',textContent:'',style:{},disabled:false,classList:{add(){},remove(){},toggle(){}},querySelectorAll(){return[]},scrollIntoView(){},focus(){}});
const nodes={app:mkNode(),progress:mkNode(),phase:mkNode(),review:mkNode(),stepSelect:mkNode(),jumpBtn:mkNode(),resetBtn:mkNode()};let cardNodes=[];
const document={getElementById(id){return nodes[id]||(nodes[id]=mkNode())},querySelectorAll(sel){return sel==='.flip-card'?cardNodes:[]},open(){},write(){},close(){}};
const storage=new Map(),location={search:'',href:'https://example.test/oraculo-v11.html'};
const window={location,scrollTo(){},open(){return null},__H93_FRATER_PHOTO:'data:image/webp;base64,TEST_PHOTO'};
const checkout={provider:'stripe',status:'awaiting_stripe_account_verification',offers:{},payment_links:{essential:{none:'',pdf:'',extra:'',pdf_extra:''},deep:{none:'',pdf:'',extra:'',pdf_extra:''},complete:{none:'',pdf:'',extra:'',pdf_extra:''},horusai:{none:''}},upsells:{magnet:{payment_link:''},numerology:{payment_link:''}}};
const sandbox={console,window,document,location,URLSearchParams,Intl,Math,Date,JSON,Number,String,Object,Array,RegExp,Promise,Set,setTimeout,clearTimeout,alert(){throw new Error('Alert inesperado')},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},fetch:async()=>({ok:true,json:async()=>checkout,text:async()=>''})};sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(runtime,sandbox,{filename:'H93-V11.1-runtime.js'});await new Promise(r=>setTimeout(r,50));
const state=()=>JSON.parse(storage.get('H93_OF_001_V11_1_STATE')||'{}');
window.startCustomQuestion();document.getElementById('entryQuestion').value='Por que eu vendo bem, mas meu faturamento nunca fica previsível e não consigo crescer?';window.refineEntryQuestion();window.acceptEntryQuestion(false);
if(!nodes.app.innerHTML.includes('geração de receita, clientes e vendas'))throw new Error('Advertorial não se adaptou ao tema vendas');
if(!nodes.app.innerHTML.includes('Por que eu vendo bem'))throw new Error('Pergunta exata não foi preservada');
window.chooseMicro(1,'repeat');window.next();if(!nodes.app.innerHTML.includes('geração de receita, clientes e vendas'))throw new Error('Pergunta de dor não foi adaptada');
window.answer('pain','vanish');window.answer('emotion','fear');window.answer('duration','months');window.chooseMicro(5,'leaks');window.next();window.chooseMicro(6,'move');window.next();
const ids=[...nodes.app.innerHTML.matchAll(/chooseCard\('([^']+)',(\d)\)/g)].map(x=>x[1]);if(ids.length!==3)throw new Error('Tiragem não exibiu 3 cartas');cardNodes=Array.from({length:3},()=>({disabled:false,classList:{add(){}}}));window.chooseCard(ids[0],0);await new Promise(r=>setTimeout(r,1000));window.chooseMicro(8,'recognition');window.next();if(!nodes.app.innerHTML.includes('agora precisa conversar com a sua pergunta'))throw new Error('Integração da carta não foi personalizada');
window.jump(13);if(!nodes.app.innerHTML.includes('Por que eu vendo bem'))throw new Error('Advertorial II perdeu a pergunta');if(!nodes.app.innerHTML.includes('Questão que organiza esta etapa'))throw new Error('Thread global ausente no Advertorial II');
window.jump(15);if(!nodes.app.innerHTML.includes('mesmo filtro da sua pergunta'))throw new Error('Prova social não foi personalizada');
window.jump(20);if(!nodes.app.innerHTML.includes('A síntese está sendo construída para a pergunta que você fez'))throw new Error('Processamento não foi personalizado');
window.jump(22);if(!nodes.app.innerHTML.includes('primeiro teste precisa responder à sua pergunta'))throw new Error('Conselho não foi personalizado');
window.jump(23);if(!nodes.app.innerHTML.includes('Seu plano agora responde ao problema'))throw new Error('Plano não foi personalizado');
window.jump(25);if(!nodes.app.innerHTML.includes('profundidade recomendada parte da sua pergunta'))throw new Error('Oferta não foi personalizada');
window.quickCheckout('essential','pdf_extra');if(!nodes.app.innerHTML.includes('Pergunta preservada nesta seleção'))throw new Error('Checkout perdeu a pergunta');
if(state().bumps.length!==2)throw new Error('Checkout perdeu complementos');
console.log(`Smoke V11.1 OK: pergunta inicial alterou advertorial, perguntas, carta, prova social, processamento, plano, oferta e checkout. Carta testada: ${ids[0]}.`);
