import fs from 'node:fs';
import vm from 'node:vm';

const html=fs.readFileSync('dist/index.html','utf8');
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(x=>x[1]);
const runtime=scripts.find(x=>x.includes("const STATE_KEY='H93_OF_001_V11_STATE'"));
if(!runtime)throw new Error('Runtime V11 ausente');
const mkNode=()=>({value:'',innerHTML:'',textContent:'',style:{},disabled:false,classList:{add(){},remove(){},toggle(){}},querySelectorAll(){return[]},scrollIntoView(){},focus(){}});
const nodes={app:mkNode(),progress:mkNode(),phase:mkNode(),review:mkNode(),stepSelect:mkNode(),jumpBtn:mkNode(),resetBtn:mkNode()};
let cardNodes=[];
const document={getElementById(id){return nodes[id]||(nodes[id]=mkNode())},querySelectorAll(sel){return sel==='.flip-card'?cardNodes:[]},open(){},write(){},close(){}};
const storage=new Map();
const location={search:'',href:'https://example.test/oraculo-v11.html'};
const window={location,scrollTo(){},open(){return null},__H93_FRATER_PHOTO:'data:image/webp;base64,TEST_PHOTO'};
const checkout={provider:'stripe',status:'awaiting_stripe_account_verification',offers:{},payment_links:{essential:{none:'',pdf:'',extra:'',pdf_extra:''},deep:{none:'',pdf:'',extra:'',pdf_extra:''},complete:{none:'',pdf:'',extra:'',pdf_extra:''},horusai:{none:''}},upsells:{magnet:{payment_link:''},numerology:{payment_link:''}}};
const sandbox={console,window,document,location,URLSearchParams,Intl,Math,Date,JSON,Number,String,Object,Array,RegExp,Promise,Set,setTimeout,clearTimeout,alert(){throw new Error('Alert inesperado')},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},fetch:async()=>({ok:true,json:async()=>checkout,text:async()=>''})};
sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(runtime,sandbox,{filename:'H93-V11-runtime.js'});await new Promise(r=>setTimeout(r,40));
const state=()=>JSON.parse(storage.get('H93_OF_001_V11_STATE')||'{}');
if(!nodes.app.innerHTML.includes('entrar ou permanecer na sua vida'))throw new Error('Headline V11 não renderizou');
if(!nodes.app.innerHTML.includes('Já tenho uma questão específica'))throw new Error('Entrada híbrida ausente');
window.setEntryMode('specific');
window.setCustomQuestion('Eu ganho dinheiro, mas ele entra e some antes de eu conseguir guardar e construir reserva.');
window.refineFinancialQuestion();
if(!state().suggestedQuestion.includes('entrar e sair'))throw new Error('Refinamento personalizado falhou');
window.useSuggestedQuestion();
if(state().step!==1)throw new Error('Pergunta aceita não avançou ao quadro 1');
let current=nodes.app.innerHTML;const micro=current.indexOf('micro-game');const cta=current.indexOf('btn btn-primary');
if(micro<0||cta<0||micro>cta)throw new Error('Microescolha ainda está abaixo do CTA');
window.chooseMicro(1,'repeat');window.next();if(state().step!==2)throw new Error('Microganho não liberou avanço');
window.answer('pain','vanish');window.answer('emotion','fear');window.answer('duration','months');
window.beginCardSelection();
if(state().step!==7||state().spread.length!==3||new Set(state().spread.map(x=>x.id)).size!==3)throw new Error('Tiragem de três posições inválida');
const ids=[...nodes.app.innerHTML.matchAll(/chooseCard\('([^']+)',(\d)\)/g)].map(x=>x[1]);
if(ids.length!==3)throw new Error('Três cartas clicáveis não renderizaram');
cardNodes=Array.from({length:3},()=>({disabled:false,classList:{add(){}}}));
window.chooseCard(ids[0],0);await new Promise(r=>setTimeout(r,1050));
if(state().step!==8)throw new Error('Carta não avançou para revelação');
if(!nodes.app.innerHTML.includes('tarot-thoth-full/'))throw new Error('Revelação não usa o acervo integral THOTH');
window.jump(14);if(!nodes.app.innerHTML.includes('data:image/webp;base64,TEST_PHOTO'))throw new Error('Foto oficial não renderizou');
window.jump(16);if((nodes.app.innerHTML.match(/v10-system-icon/g)||[]).length<6)throw new Error('Seis sistemas visuais não renderizaram');
window.jump(25);for(const variant of ['none','pdf','extra','pdf_extra'])if(!nodes.app.innerHTML.includes(`quickCheckout('essential','${variant}')`))throw new Error(`Variação comercial ausente: ${variant}`);
window.quickCheckout('essential','pdf_extra');if(state().step!==26||state().bumps.length!==2)throw new Error('Combinação plano+2 complementos não chegou ao checkout');
if(!nodes.app.innerHTML.includes('CHECKOUT AGUARDANDO LIBERAÇÃO DA STRIPE')||!nodes.app.innerHTML.includes('disabled'))throw new Error('Checkout bloqueado não está seguro');
console.log(`Smoke V11 OK: pergunta híbrida, microganho, posição da caixa, deck integral, revelação, foto, sistemas e quatro variações comerciais validados. Carta testada: ${ids[0]}.`);
